// Express + EJS server for the IT Inventory dashboard.
// - EJS views live in views/pages/ and share partials from views/partials/
//   (head, topbar, sidebar, footer, scripts, scripts-auth).
// - Static assets (assets/, fonts.*/, _DataURI/, docs/, prisma/, etc.) are
//   served from the project root.
//
// Usage:
//   npm start        # production-style, no auto-reload
//   npm run dev      # nodemon watches this file and the static assets
//
// Then open http://127.0.0.1:3000/

const fs = require('fs');
const path = require('path');
const express = require('express');
const session = require('express-session');
const bcrypt = require('bcrypt');
const { PrismaClient } = require('@prisma/client');

const app = express();
const prisma = new PrismaClient();

// Body parsing for CRUD POSTs (form submissions).
app.use(express.urlencoded({ extended: true, limit: '1mb' }));

// Session middleware — memory store (dev only; swap to Redis/DB for production)
app.use(session({
  secret: process.env.SESSION_SECRET || 'inventory-dev-secret-change-in-production',
  resave: false,
  saveUninitialized: false,
  cookie: {
    httpOnly: true,
    secure: false, // set true behind HTTPS
    maxAge: 24 * 60 * 60 * 1000, // 24 hours
  },
}));

// Don't advertise the runtime in responses.
app.disable('x-powered-by');

// EJS view engine. The pages/ folder is the implicit root, so a page is
// rendered as res.render('pages/<name>').
app.set('view engine', 'ejs');
app.set('views', path.join(__dirname, 'views'));

// page-name -> human title map. Generated by scripts/convert-to-ejs.js so that
// the <title> tag in the head partial can show the right page name.
const TITLES = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'views', 'titles.json'), 'utf8')
);

const PORT = Number(process.env.PORT) || 3000;
const HOST = process.env.HOST || '127.0.0.1';
const MAX_PORT_ATTEMPTS = 10;
const ROOT_DIR = __dirname;

// Async error wrapper for Express 4.x — catches rejected promises in async
// route handlers and forwards them to the Express error handler.
const asyncHandler = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);

// Disable HTTP caching in dev so every refresh picks up the latest HTML/CSS/JS.
app.use((req, res, next) => {
  res.set('Cache-Control', 'no-store, no-cache, must-revalidate, proxy-revalidate');
  res.set('Pragma', 'no-cache');
  res.set('Expires', '0');
  next();
});

// Request log – one line per request, no extra dep.
app.use((req, _res, next) => {
  console.log(`[${new Date().toISOString()}] ${req.method} ${req.url}`);
  next();
});

// ----------------------------------------------------------------------
// EJS routes — must come BEFORE the static middleware so that .html URLs
// render the matching views/pages/<name>.ejs instead of the (now removed)
// root HTML files.
// ----------------------------------------------------------------------

// ----------------------------------------------------------------------
// Authentication routes — login, logout
// ----------------------------------------------------------------------

// GET /login — show login form
app.get('/login', (req, res) => {
  if (req.session.userId) return res.redirect('/');
  res.render('pages/auth-login', { title: 'Login', error: null, message: null });
});

// POST /login — authenticate user
app.post('/login', async (req, res) => {
  const { email, password } = req.body || {};
  if (!email || !password) {
    return res.status(400).render('pages/auth-login', { title: 'Login', error: 'Email and password are required.', message: null });
  }
  try {
    // Find user by email across all tenants (email is unique per tenant via
    // tenantId_email compound key, so findFirst across tenants works at login).
    const user = await prisma.user.findFirst({
      where: { email },
      include: { tenant: true, role: true },
    });
    if (!user) {
      return res.status(401).render('pages/auth-login', { title: 'Login', error: 'Invalid email or password.', message: null });
    }
    const valid = await bcrypt.compare(password, user.passwordHash);
    if (!valid) {
      return res.status(401).render('pages/auth-login', { title: 'Login', error: 'Invalid email or password.', message: null });
    }
    // Update lastLoginAt — fire-and-forget so it doesn't delay the redirect
    prisma.user.update({ where: { id: user.id }, data: { lastLoginAt: new Date() } }).catch(() => {});
    // Regenerate session to prevent session fixation
    const redirectTo = req.session.returnTo || '/';
    req.session.regenerate(() => {
      req.session.userId   = user.id;
      req.session.tenantId = user.tenantId;
      req.session.tenantSlug = user.tenant ? user.tenant.slug : null;
      req.session.userName = user.fullName;
      req.session.userRole = user.role ? user.role.name.toUpperCase().replace(/ /g, '_') : null;
      res.redirect(redirectTo);
    });
  } catch (err) {
    console.error('Login error:', err);
    res.status(500).render('pages/auth-login', { title: 'Login', error: 'An error occurred. Please try again.', message: null });
  }
});

// GET /logout — destroy session and redirect to login
app.get('/logout', (req, res) => {
  req.session.destroy(() => {
    res.redirect('/login');
  });
});

// Auth guard middleware — redirects to /login if not authenticated.
// Saves the intended URL so the login handler can redirect back after success.
function requireAuth(req, res, next) {
  if (req.session && req.session.userId) return next();
  req.session.returnTo = req.originalUrl;
  res.redirect('/login');
}

// ----------------------------------------------------------------------
// Role-based access control (RBAC)
// ----------------------------------------------------------------------

// Permission list:
//   assets:read / assets:write
//   lifecycle:read / lifecycle:write
//   directory:read / directory:write
//   inventory:read / inventory:write
//   admin:read / admin:write
//   communications:read / communications:write
const PERMISSIONS = {
  IT_MANAGER: [
    'assets:read', 'assets:write',
    'lifecycle:read', 'lifecycle:write',
    'directory:read', 'directory:write',
    'inventory:read', 'inventory:write',
    'admin:read', 'admin:write',
    'communications:read', 'communications:write',
  ],
  IT_SUPPORT: [
    'assets:read', 'assets:write',
    'lifecycle:read', 'lifecycle:write',
    'directory:read',
    'inventory:read',
    'admin:read',
    'communications:read',
  ],
  DEPARTMENT_HEAD: [
    'assets:read',
    'lifecycle:read',
    'directory:read',
  ],
  EMPLOYEE: [
    'assets:read',
    'lifecycle:read',
  ],
};

// Middleware factory — returns a middleware that checks the given permission.
// Must be placed after requireAuth (which ensures req.session.userRole exists).
function can(permission) {
  return (req, res, next) => {
    const role = req.session.userRole;
    const allowed = PERMISSIONS[role] || [];
    if (!allowed.includes(permission)) {
      return res.status(403).render('pages/pages-404', {
        title: 'Access Denied',
        errorMessage: 'You do not have permission to access this page.',
      });
    }
    next();
  };
}

// Permission look-up for the wildcard .html route — maps page name to required
// permission so the bypass route can't skirt RBAC.
const PAGE_PERMISSIONS = {
  index:           null,            // dashboard — auth-only
  assets:         'assets:read',
  vendors:        'directory:read',
  locations:      'directory:read',
  categories:     'directory:read',
  users:          'directory:read',
  assignments:    'lifecycle:read',
  maintenance:    'lifecycle:read',
  licenses:       'inventory:read',
  departments:    'directory:read',
  approvals:      'lifecycle:read',
  'license-seats': 'inventory:read',
  warranty:       'lifecycle:read',
  roles:          'admin:read',
  'audit-log':    'admin:read',
  reports:        'admin:read',
  notifications:  'communications:read',
  webhooks:       'communications:read',
  profile:         null,            // profile — auth-only
};

// Layout locals for all rendered pages — inject user info + permissions
app.use((req, res, next) => {
  const role = req.session.userRole;
  res.locals.currentUser = req.session.userId ? {
    id: req.session.userId,
    fullName: req.session.userName,
    role: role,
    tenantSlug: req.session.tenantSlug,
  } : null;
  res.locals.userPermissions = role ? (PERMISSIONS[role] || []) : [];
  next();
});

// Set request context for prismaData.js tenant resolution
app.use((req, _res, next) => {
  prismaData.setRequest(req);
  next();
});

// Profile page — all authenticated users can see their own profile
app.get('/profile', requireAuth, async (req, res) => {
  res.render('pages/profile', {
    title:   'My Profile',
    success: null,
    error:   null,
  });
});

// POST /profile/password — change password
app.post('/profile/password', requireAuth, async (req, res) => {
  const { currentPassword, newPassword, confirmPassword } = req.body || {};
  // Validation
  if (!currentPassword || !newPassword || !confirmPassword) {
    return res.status(400).render('pages/profile', {
      title:   'My Profile',
      success: null,
      error:   'All fields are required.',
    });
  }
  if (newPassword.length < 6) {
    return res.status(400).render('pages/profile', {
      title:   'My Profile',
      success: null,
      error:   'New password must be at least 6 characters.',
    });
  }
  if (newPassword !== confirmPassword) {
    return res.status(400).render('pages/profile', {
      title:   'My Profile',
      success: null,
      error:   'New password and confirmation do not match.',
    });
  }
  try {
    // Look up user and verify current password
    const user = await prisma.user.findUnique({ where: { id: req.session.userId } });
    if (!user) {
      return res.status(400).render('pages/profile', {
        title:   'My Profile',
        success: null,
        error:   'User not found.',
      });
    }
    const valid = await bcrypt.compare(currentPassword, user.passwordHash);
    if (!valid) {
      return res.status(400).render('pages/profile', {
        title:   'My Profile',
        success: null,
        error:   'Current password is incorrect.',
      });
    }
    if (currentPassword === newPassword) {
      return res.status(400).render('pages/profile', {
        title:   'My Profile',
        success: null,
        error:   'New password must be different from current password.',
      });
    }
    // Hash new password, update, and regenerate session for security
    const hash = await bcrypt.hash(newPassword, 12);
    await prisma.user.update({ where: { id: user.id }, data: { passwordHash: hash } });
    req.session.regenerate(() => {
      req.session.userId   = user.id;
      req.session.tenantId = user.tenantId;
      req.session.tenantSlug = req.session.tenantSlug;
      req.session.userName = user.fullName;
      req.session.userRole = req.session.userRole;
      res.render('pages/profile', {
        title:   'My Profile',
        success: 'Password changed successfully.',
        error:   null,
      });
    });
  } catch (err) {
    console.error('Password change error:', err);
    res.status(500).render('pages/profile', {
      title:   'My Profile',
      success: null,
      error:   'An error occurred. Please try again.',
    });
  }
});

// Root — all authenticated users can see the dashboard
app.get('/', requireAuth, async (_req, res) => {
  res.render('pages/index', {
    title: TITLES['index'] || 'Dashboard',
    pageScripts: ['assets/libs/apexcharts/apexcharts.min.js', 'assets/js/pages/dashboard.init.js'],
  });
});

// API — dashboard statistics (used by the ApexCharts dashboard.init.js)
app.get('/api/dashboard/stats', requireAuth, async (_req, res) => {
  try {
    const tid = _req.session.tenantId;
    const [
      allAssets,
      totalUsers,
      totalVendors,
      totalLocations,
      recentAudit,
    ] = await Promise.all([
      prisma.asset.findMany({ where: { tenantId: tid }, select: { status: true, categoryId: true } }),
      prisma.user.count({ where: { tenantId: tid } }),
      prisma.vendor.count({ where: { tenantId: tid } }),
      prisma.location.count({ where: { tenantId: tid } }),
      prisma.auditLog.findMany({ where: { tenantId: tid }, include: { user: true }, orderBy: { createdAt: 'desc' }, take: 10 }),
    ]);

    // Group by status in JS
    const statusMap = {};
    allAssets.forEach(a => {
      statusMap[a.status] = (statusMap[a.status] || 0) + 1;
    });
    const assetsByStatus = Object.entries(statusMap).map(([status, count]) => ({ status, count }));

    // Group by category in JS
    const catMap = {};
    allAssets.forEach(a => {
      if (a.categoryId) catMap[a.categoryId] = (catMap[a.categoryId] || 0) + 1;
    });
    // Resolve category names
    const categoryIds = Object.keys(catMap);
    const categories = categoryIds.length
      ? await prisma.category.findMany({ where: { id: { in: categoryIds } } })
      : [];
    const nameMap = {};
    categories.forEach(c => { nameMap[c.id] = c.name; });
    const assetsByCategory = Object.entries(catMap)
      .map(([catId, count]) => ({ category: nameMap[catId] || 'Uncategorized', count }))
      .sort((a, b) => b.count - a.count)
      .slice(0, 8);

    res.json({
      totalAssets: allAssets.length,
      assetsByStatus,
      assetsByCategory,
      totalUsers,
      totalVendors,
      totalLocations,
      recentActivity: recentAudit.map(e => ({
        action: e.action,
        entityType: e.entityType,
        entityId: e.entityId,
        userName: e.user ? e.user.fullName : 'System',
        createdAt: e.createdAt,
      })),
    });
  } catch (err) {
    console.error('Dashboard stats error:', err);
    res.status(500).json({ error: 'Failed to load dashboard statistics.' });
  }
});

// API — dashboard 7-day trends (sparkline data for the stat cards).
//   Returns counts per day for the last 7 days (oldest -> newest).
//   Each metric is numerically aligned with the `labels` array so the
//   client can render Apache-style sparklines without re-pivoting.
app.get('/api/dashboard/trends', requireAuth, async (_req, res) => {
  try {
    const tid = _req.session.tenantId;
    const DAYS = 7;
    // Build the 7 day-buckets (midnight..midnight) ending today, oldest first.
    const now = new Date();
    const startOfToday = new Date(now.getFullYear(), now.getMonth(), now.getDate());
    const buckets = [];
    for (let i = DAYS - 1; i >= 0; i--) {
      const d = new Date(startOfToday);
      d.setDate(d.getDate() - i);
      buckets.push(d);
    }
    const from = buckets[0];
    const labels = buckets.map(d => d.toISOString().slice(0, 10));
    const inWindow = { createdAt: { gte: from } };

    const [assetsRaw, usersRaw, assignmentsRaw, vendorsRaw] = await Promise.all([
      prisma.asset.findMany({ where: { tenantId: tid, ...inWindow }, select: { createdAt: true } }),
      prisma.user.findMany({ where: { tenantId: tid, ...inWindow }, select: { createdAt: true } }),
      prisma.assignment.findMany({ where: { tenantId: tid, ...inWindow }, select: { assignedAt: true } }),
      prisma.vendor.findMany({ where: { tenantId: tid, ...inWindow }, select: { createdAt: true } }),
    ]);

    // Bucket-by-day helper. Counts rows whose date falls in [buckets[i], buckets[i+1]).
    function bucketize(records, getDate) {
      const counts = new Array(DAYS).fill(0);
      for (const r of records) {
        const d = getDate(r);
        if (!d) continue;
        const t = d.getTime();
        for (let i = 0; i < DAYS; i++) {
          const lo = buckets[i].getTime();
          const hi = i + 1 < DAYS ? buckets[i + 1].getTime() : startOfToday.getTime() + 24 * 60 * 60 * 1000;
          if (t >= lo && t < hi) { counts[i]++; break; }
        }
      }
      return counts;
    }

    res.json({
      labels,
      assets:       bucketize(assetsRaw, r => r.createdAt),
      users:        bucketize(usersRaw, r => r.createdAt),
      assignments:  bucketize(assignmentsRaw, r => r.assignedAt),
      vendors:      bucketize(vendorsRaw, r => r.createdAt),
    });
  } catch (err) {
    console.error('Dashboard trends error:', err);
    res.status(500).json({ error: 'Failed to load dashboard trends.' });
  }
});

// Error pages — set the right HTTP status before rendering the template.
app.get('/pages-404.html', (_req, res) => {
  res.status(404).render('pages/pages-404', { title: TITLES['pages-404'] || '404' });
});
app.get('/pages-500.html', (_req, res) => {
  res.status(500).render('pages/pages-500', { title: TITLES['pages-500'] || '500' });
});

// All other *.html URLs → render the matching EJS view.
// Only unauthenticated pages that are safe to serve without auth:
// auth-*, pages-4*, pages-5*
const PUBLIC_PAGES = /^(auth|pages-4|pages-5)/;
app.get('/:page.html', (req, res, next) => {
  const page = req.params.page;
  // Defensive: only allow simple, single-segment page names. This blocks any
  // attempt to escape views/pages/ (e.g. via ".." or path tricks) and ensures
  // we only ever render files we actually generated from the Clarity template (originally a Minia fork).
  if (!/^[a-zA-Z0-9_-]+$/.test(page)) return next();
  // Require auth for all non-public pages (blocks /assets.html, /vendors.html, etc.)
  if (!PUBLIC_PAGES.test(page) && (!req.session || !req.session.userId)) {
    req.session.returnTo = req.originalUrl;
    return res.redirect('/login');
  }
  // Check RBAC for non-public pages that match a known permission
  if (!PUBLIC_PAGES.test(page) && PAGE_PERMISSIONS.hasOwnProperty(page)) {
    const required = PAGE_PERMISSIONS[page];
    if (required) {
      const role = req.session.userRole;
      const allowed = PERMISSIONS[role] || [];
      if (!allowed.includes(required)) {
        return res.status(403).render('pages/pages-404', {
          title: 'Access Denied',
          errorMessage: 'You do not have permission to access this page.',
        });
      }
    }
  }
  const viewPath = path.join(__dirname, 'views', 'pages', page + '.ejs');
  if (fs.existsSync(viewPath)) {
    res.render('pages/' + page, { title: TITLES[page] || page });
  } else {
    next(); // fall through to 404
  }
});

// ----------------------------------------------------------------------
// Asset routes (Phase 1 of the IT inventory UI). mockData.js returns objects
// shaped exactly like Prisma will return in Phase 6, so the route handlers
// can swap from `mockData.getAssets(...)` to `prisma.asset.findMany(...)`
// with no EJS changes.
// ----------------------------------------------------------------------
const prismaData = require('./views/lib/prismaData');

app.get('/assets', requireAuth, can('assets:read'), async (req, res) => {
  const result = await prismaData.getAssets({
    status:       req.query.status       || undefined,
    categoryId:   req.query.categoryId   || undefined,
    locationId:   req.query.locationId   || undefined,
    vendorId:     req.query.vendorId     || undefined,
    assignedOnly: req.query.assignedOnly === '1',
    search:       req.query.search       || undefined,
    page:         Number(req.query.page)  || 1,
  });
  res.render('pages/assets/index', {
    title:      TITLES['assets'] || 'Assets',
    query:      req.query,
    result:     result,
    assetsAll:  await prismaData.getAssets(),
    categories: await prismaData.getCategories(),
    locations:  await prismaData.getLocations(),
    vendors:    await prismaData.getVendors(),
  });
});

app.get('/assets/new', requireAuth, can('assets:write'), async (_req, res) => {
  res.render('pages/assets/new', {
    title:      TITLES['assets/new'] || 'New Asset',
    categories: await prismaData.getCategories(),
    vendors:    await prismaData.getVendors(),
    locations:  await prismaData.getLocations(),
  });
});

app.get('/assets/:id', requireAuth, can('assets:read'), async (req, res, next) => {
  const asset = await prismaData.getAssetById(req.params.id);
  if (!asset) return next();
  res.render('pages/assets/detail', {
    title:       asset.name,
    asset:       asset,
    assignments: await prismaData.getAssignmentsForAsset(asset.id),
    maintenance: await prismaData.getMaintenanceForAsset(asset.id),
    users:       await prismaData.getUsers(),
  });
});

app.get('/assets/:id/edit', requireAuth, can('assets:write'), async (req, res, next) => {
  const asset = await prismaData.getAssetById(req.params.id);
  if (!asset) return next();
  res.render('pages/assets/edit', {
    title:      'Edit ' + asset.name,
    asset:      asset,
    categories: await prismaData.getCategories(),
    vendors:    await prismaData.getVendors(),
    locations:  await prismaData.getLocations(),
  });
});

app.get('/assets/:id/qr', requireAuth, can('assets:read'), async (req, res, next) => {
  const asset = await prismaData.getAssetById(req.params.id);
  if (!asset) return next();
  res.render('pages/assets/qr', {
    title: 'Print QR - ' + asset.name,
    asset: asset,
  });
});

// ----------------------------------------------------------------------
// Directory / lifecycle / inventory list pages (added for the new sidebar nav).
// Data-driven pages pass rows straight from mockData.js. Stub pages (licenses,
// departments, approvals) just render an empty-state banner — the views
// handle the "no data" branch themselves, so we don't need to inject empty
// arrays from the route.
// ----------------------------------------------------------------------

// Dedicated user detail route — defined before the CRUD loop so it takes
// precedence over the generic GET /users/:id handler. Shows enriched data.
app.get('/users/:id', requireAuth, can('directory:read'), async (req, res, next) => {
  const user = await prismaData.getUserDetail(req.params.id);
  if (!user) return next();
  res.render('pages/users/detail', {
    title:       user.fullName,
    slug:        'users',
    row:         user,
    user:        user,
    schema:      schemas['users'] || [],
    sources:     await getSources('users'),
    parentCrumb: 'Directory',
    capLc:       'user',
    cap:         'User',
    errors:      {},
  });
});

// Directory — model-driven, mockData-backed
app.get('/vendors', requireAuth, can('directory:read'), async (req, res) => {
  let rows = await prismaData.getVendors();
  const search = req.query.search || '';
  const status = req.query.status || '';
  if (search) {
    const q = search.toLowerCase();
    rows = rows.filter(v =>
      v.name.toLowerCase().includes(q) ||
      (v.contactPerson || '').toLowerCase().includes(q) ||
      (v.email || '').toLowerCase().includes(q)
    );
  }
  if (status) {
    rows = rows.filter(v => v.status === status);
  }
  res.render('pages/vendors/index', {
    title:   'Vendors',
    slug:    'vendors',
    query:   req.query,
    vendors: rows,
    schema:  schemas['vendors'] || [],
    sources: await getSources('vendors'),
    statusOptions: ['', 'ACTIVE', 'INACTIVE'],
  });
});

app.get('/locations', requireAuth, can('directory:read'), async (req, res) => {
  let rows = await prismaData.getLocations();
  const search = req.query.search || '';
  if (search) {
    const q = search.toLowerCase();
    rows = rows.filter(l => l.name.toLowerCase().includes(q) || (l.address || '').toLowerCase().includes(q));
  }
  res.render('pages/locations/index', {
    title:     'Locations',
    slug:      'locations',
    query:     req.query,
    locations: rows,
    schema:    schemas['locations'] || [],
    sources:   await getSources('locations'),
  });
});

app.get('/categories', requireAuth, can('directory:read'), async (req, res) => {
  let rows = await prismaData.getCategories();
  const search = req.query.search || '';
  const type   = req.query.status || '';
  if (search) {
    const q = search.toLowerCase();
    rows = rows.filter(c => c.name.toLowerCase().includes(q));
  }
  if (type) rows = rows.filter(c => c.type === type);
  res.render('pages/categories/index', {
    title:         'Categories',
    slug:          'categories',
    query:         req.query,
    categories:    rows,
    schema:        schemas['categories'] || [],
    sources:       await getSources('categories'),
    statusOptions: ['', 'HARDWARE', 'SOFTWARE', 'PERIPHERAL', 'ACCESSORY'],
  });
});

app.get('/users', requireAuth, can('directory:read'), async (req, res) => {
  let rows = await prismaData.getUsers();
  const search = req.query.search || '';
  const role   = req.query.status || '';
  if (search) {
    const q = search.toLowerCase();
    rows = rows.filter(u => u.fullName.toLowerCase().includes(q) || u.email.toLowerCase().includes(q));
  }
  if (role) rows = rows.filter(u => u.role === role);
  res.render('pages/users/index', {
    title:         'Users',
    slug:          'users',
    query:         req.query,
    users:         rows,
    schema:        schemas['users'] || [],
    sources:       await getSources('users'),
    statusOptions: ['', 'IT_MANAGER', 'IT_SUPPORT', 'DEPARTMENT_HEAD', 'EMPLOYEE'],
  });
});

// Lifecycle — flat assignments + maintenance listings (added as global accessors to mockData)
app.get('/assignments', requireAuth, can('lifecycle:read'), async (req, res) => {
  let rows = await prismaData.getAssignments();
  const search = req.query.search || '';
  if (search) {
    const q = search.toLowerCase();
    rows = rows.filter(a =>
      (a.assetId || '').toLowerCase().includes(q) ||
      (a.user && a.user.fullName || '').toLowerCase().includes(q)
    );
  }
  res.render('pages/assignments/index', {
    title:       'Assignments',
    slug:        'assignments',
    query:       req.query,
    assignments: rows,
    schema:      schemas['assignments'] || [],
    sources:     await getSources('assignments'),
  });
});

app.get('/maintenance', requireAuth, can('lifecycle:read'), async (req, res) => {
  let rows = await prismaData.getMaintenance();
  const search = req.query.search || '';
  const status = req.query.status || '';
  if (search) {
    const q = search.toLowerCase();
    rows = rows.filter(m =>
      (m.description || '').toLowerCase().includes(q) ||
      (m.vendor && m.vendor.name || '').toLowerCase().includes(q) ||
      (m.ticketNumber || '').toLowerCase().includes(q)
    );
  }
  if (status) rows = rows.filter(m => m.status === status);
  res.render('pages/maintenance/index', {
    title:         'Maintenance',
    slug:          'maintenance',
    query:         req.query,
    maintenance:   rows,
    schema:        schemas['maintenance'] || [],
    statusOptions: ['', 'OPEN', 'IN_PROGRESS', 'COMPLETED', 'CLOSED'],
  });
});

// Inventory/Lifecycle stubs — Phase 6 (Prisma) wiring only; views render empty-state
// Pass an empty array so the toolbar + table-or-empty-state pattern works.
app.get('/licenses', requireAuth, can('inventory:read'), async (req, res) => {
  let rows = typeof prismaData.listLicenses === 'function' ? await prismaData.listLicenses() : [];
  const search = req.query.search || '';
  if (search) {
    const q = search.toLowerCase();
    rows = rows.filter(l => l.name.toLowerCase().includes(q) || (l.licenseKey || '').toLowerCase().includes(q));
  }
  res.render('pages/licenses/index', {
    title:    'Software Licenses',
    slug:     'licenses',
    query:    req.query,
    licenses: rows,
    schema:   schemas['licenses'] || [],
  });
});
app.get('/departments', requireAuth, can('directory:read'), async (req, res) => {
  let rows = typeof prismaData.listDepartments === 'function' ? await prismaData.listDepartments() : [];
  const search = req.query.search || '';
  if (search) {
    const q = search.toLowerCase();
    rows = rows.filter(d => d.name.toLowerCase().includes(q) || (d.code || '').toLowerCase().includes(q));
  }
  res.render('pages/departments/index', {
    title:       'Departments',
    slug:        'departments',
    query:       req.query,
    departments: rows,
    schema:      schemas['departments'] || [],
    sources:     await getSources('departments'),
  });
});
app.get('/approvals', requireAuth, can('lifecycle:read'), async (req, res) => {
  let rows = typeof prismaData.listApprovals === 'function' ? await prismaData.listApprovals() : [];
  const search = req.query.search || '';
  const status = req.query.status || '';
  if (search) {
    const q = search.toLowerCase();
    rows = rows.filter(a => (a.entityType || '').toLowerCase().includes(q) || (a.entityId || '').toLowerCase().includes(q));
  }
  if (status) rows = rows.filter(a => a.status === status);
  res.render('pages/approvals/index', {
    title:         'Approvals',
    slug:          'approvals',
    query:         req.query,
    approvals:     rows,
    schema:        schemas['approvals'] || [],
    sources:       await getSources('approvals'),
    statusOptions: ['', 'PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'],
  });
});

// ----------------------------------------------------------------------
// PRO sidebar pages — inventory, lifecycle, admin, communications.
// All render empty-state stubs wired for Phase 6 Prisma swap.
// ----------------------------------------------------------------------

app.get('/license-seats', requireAuth, can('inventory:read'), async (req, res) => {
  let rows = await prismaData.getLicenseSeats();
  const search = req.query.search || '';
  if (search) {
    const q = search.toLowerCase();
    rows = rows.filter(s =>
      (s.licenseName || '').toLowerCase().includes(q) ||
      (s.assetName || '').toLowerCase().includes(q) ||
      (s.userName || '').toLowerCase().includes(q)
    );
  }
  res.render('pages/license-seats/index', {
    title:  'License Seats',
    slug:   'license-seats',
    query:  req.query,
    seats:  rows,
    schema: schemas['license-seats'] || [],
  });
});

app.get('/warranty', requireAuth, can('lifecycle:read'), async (req, res) => {
  let rows = await prismaData.getWarranties();
  const search = req.query.search || '';
  const status = req.query.status || '';
  if (search) {
    const q = search.toLowerCase();
    rows = rows.filter(w =>
      (w.assetName || '').toLowerCase().includes(q) ||
      (w.assetTag || '').toLowerCase().includes(q)
    );
  }
  if (status) rows = rows.filter(w => w.status === status);
  res.render('pages/warranty/index', {
    title:         'Warranty Tracking',
    slug:          'warranty',
    query:         req.query,
    warranties:    rows,
    schema:        schemas['warranty'] || [],
    statusOptions: ['', 'ACTIVE', 'EXPIRING', 'EXPIRED'],
  });
});

app.get('/roles', requireAuth, can('admin:read'), async (req, res) => {
  let rows = await prismaData.getRoles();
  const search = req.query.search || '';
  if (search) {
    const q = search.toLowerCase();
    rows = rows.filter(r =>
      r.name.toLowerCase().includes(q) ||
      (r.description || '').toLowerCase().includes(q)
    );
  }
  res.render('pages/roles/index', {
    title:  'Roles & Permissions',
    slug:   'roles',
    query:  req.query,
    roles:  rows,
    schema: schemas['roles'] || [],
  });
});

app.get('/audit-log', requireAuth, can('admin:read'), async (req, res) => {
  let rows = await prismaData.getAuditLogs();
  const search = req.query.search || '';
  if (search) {
    const q = search.toLowerCase();
    rows = rows.filter(e =>
      (e.action || '').toLowerCase().includes(q) ||
      (e.entityType || '').toLowerCase().includes(q) ||
      (e.entityId || '').toLowerCase().includes(q) ||
      ((e.user && e.user.fullName) || '').toLowerCase().includes(q)
    );
  }
  res.render('pages/audit-log/index', {
    title:   'Audit Log',
    slug:    'audit-log',
    query:   req.query,
    entries: rows,
    schema:  schemas['audit-log'] || [],
  });
});

app.get('/reports', requireAuth, can('admin:read'), async (req, res) => {
  let rows = prismaData.getReports();
  const search = req.query.search || '';
  if (search) {
    const q = search.toLowerCase();
    rows = rows.filter(r => (r.name || '').toLowerCase().includes(q));
  }
  res.render('pages/reports/index', {
    title:   'Reports',
    slug:    'reports',
    query:   req.query,
    reports: rows,
    schema:  schemas['reports'] || [],
  });
});

app.get('/notifications', requireAuth, can('communications:read'), async (req, res) => {
  let rows = await prismaData.getNotifications();
  const search = req.query.search || '';
  const status = req.query.status || '';
  if (search) {
    const q = search.toLowerCase();
    rows = rows.filter(n =>
      (n.title || '').toLowerCase().includes(q) ||
      (n.body || '').toLowerCase().includes(q)
    );
  }
  if (status === 'READ') rows = rows.filter(n => n.readAt != null);
  else if (status === 'UNREAD') rows = rows.filter(n => n.readAt == null);
  res.render('pages/notifications/index', {
    title:         'Notifications',
    slug:          'notifications',
    query:         req.query,
    notifications: rows,
    schema:        schemas['notifications'] || [],
    statusOptions: ['', 'UNREAD', 'READ'],
  });
});

app.get('/webhooks', requireAuth, can('communications:read'), async (req, res) => {
  let rows = await prismaData.getWebhooks();
  const search = req.query.search || '';
  const channel = req.query.status || '';
  if (search) {
    const q = search.toLowerCase();
    rows = rows.filter(w =>
      (w.url || '').toLowerCase().includes(q) ||
      (w.events || []).some(ev => ev.toLowerCase().includes(q))
    );
  }
  if (channel) rows = rows.filter(w => w.channel === channel);
  res.render('pages/webhooks/index', {
    title:         'Webhooks',
    slug:          'webhooks',
    query:         req.query,
    webhooks:      rows,
    schema:        schemas['webhooks'] || [],
    statusOptions: ['', 'SLACK', 'TEAMS'],
  });
});

// ----------------------------------------------------------------------
// Role CRUD — dedicated routes (not in the auto-CRUD loop). See the
// comment block in views/lib/prismaData.js for why this is hand-written.
// express.urlencoded({extended:true}) parses `name="permissions[]"`
// repeated fields into req.body.permissions as a string[].
// NOTE: /roles/new is registered BEFORE /roles/:id so Express matches
// the literal route first when both could match (e.g. an id of "new").
// ----------------------------------------------------------------------

// GET /roles/new — admin:read so anyone able to view the index can also
// reach the create form. POST /roles below gates the actual write.
app.get('/roles/new', requireAuth, can('admin:read'), async (_req, res) => {
  res.render('pages/roles/new', {
    title:       'New Role',
    slug:        'roles',
    row:         { permissions: [] },
    sources:     { permissions: await prismaData.getPermissions() },
    groups:      prismaData.PERMISSION_GROUPS,
    parentCrumb: 'Admin',
    cap:         'Role',
    capLc:       'role',
    errors:      {},
  });
});

// POST /roles — create a new role with its permission set. Server-side
// builtin=false enforcement so the UI can't sneak a system role past us.
app.post('/roles', requireAuth, can('admin:write'), async (req, res) => {
  const result = await prismaData.createRole(req.body || {});
  if (!result.success) {
    return res.status(400).render('pages/roles/new', {
      title:       'New Role',
      slug:        'roles',
      row:         Object.assign({}, req.body || {}, { permissions: prismaData.parsePermissionCodes(req.body || {}) }),
      sources:     { permissions: await prismaData.getPermissions() },
      groups:      prismaData.PERMISSION_GROUPS,
      parentCrumb: 'Admin',
      cap:         'Role',
      capLc:       'role',
      errors:      result.errors,
    });
  }
  res.redirect('/roles/' + result.data.id);
});

// GET /roles/:id — read-only detail (works for builtins too, just no edit/delete buttons).
app.get('/roles/:id', requireAuth, can('admin:read'), async (req, res, next) => {
  const row = await prismaData.getRoleById(req.params.id);
  if (!row) return next();
  res.render('pages/roles/detail', {
    title:       row.name,
    slug:        'roles',
    row,
    sources:     { permissions: await prismaData.getPermissions() },
    groups:      prismaData.PERMISSION_GROUPS,
    parentCrumb: 'Admin',
    cap:         'Role',
    capLc:       'role',
    errors:      {},
  });
});

// GET /roles/:id/edit
app.get('/roles/:id/edit', requireAuth, can('admin:read'), async (req, res, next) => {
  const row = await prismaData.getRoleById(req.params.id);
  if (!row) return next();
  res.render('pages/roles/edit', {
    title:       'Edit ' + row.name,
    slug:        'roles',
    row:         Object.assign({}, row, { permissions: row.permissionCodes || [] }),
    sources:     { permissions: await prismaData.getPermissions() },
    groups:      prismaData.PERMISSION_GROUPS,
    parentCrumb: 'Admin',
    cap:         'Role',
    capLc:       'role',
    errors:      {},
  });
});

// POST /roles/:id — update an existing role. Builtin protection is
// enforced inside prismaData.updateRole (name is held; description +
// permissions remain mutable so an admin can clarify a builtin).
app.post('/roles/:id', requireAuth, can('admin:write'), async (req, res, next) => {
  const existing = await prismaData.getRoleById(req.params.id);
  if (!existing) return next();
  const result = await prismaData.updateRole(req.params.id, req.body || {});
  if (!result.success) {
    const resubmittedPerms = prismaData.parsePermissionCodes(req.body || {});
    return res.status(400).render('pages/roles/edit', {
      title:       'Edit ' + existing.name,
      slug:        'roles',
      row:         Object.assign({}, existing, req.body || {}, { permissions: resubmittedPerms }),
      sources:     { permissions: await prismaData.getPermissions() },
      groups:      prismaData.PERMISSION_GROUPS,
      parentCrumb: 'Admin',
      cap:         'Role',
      capLc:       'role',
      errors:      result.errors,
    });
  }
  res.redirect('/roles/' + req.params.id);
});

// POST /roles/:id/delete — block builtins server-side; gracefully surface
// FK-Restrict failures (users still attached to this role) as inline errors.
app.post('/roles/:id/delete', requireAuth, can('admin:write'), async (req, res) => {
  const result = await prismaData.deleteRole(req.params.id);
  if (result.success) return res.redirect('/roles');
  const row = await prismaData.getRoleById(req.params.id) || { id: req.params.id, name: 'Role' };
  res.status(400).render('pages/roles/detail', {
    title:       row.name,
    slug:        'roles',
    row,
    sources:     { permissions: await prismaData.getPermissions() },
    groups:      prismaData.PERMISSION_GROUPS,
    parentCrumb: 'Admin',
    cap:         'Role',
    capLc:       'role',
    errors:      result.errors,
  });
});

// ----------------------------------------------------------------------
// Static assets — every other file in the project root (assets/, fonts.*/,
// _DataURI/, docs/, prisma/, server.js, package.json, etc.). We do NOT
// serve *.html here; the EJS routes above own those URLs.
// ----------------------------------------------------------------------
// ----------------------------------------------------------------------
// CRUD routes for the 9 sidebar nav modules — auto-generated new / detail /
// edit / create / update / delete routes per module. Routes share the
// schemas.js field shapes (also read by mockData mutators and the
// views/partials/crud-form.ejs renderer).
// ----------------------------------------------------------------------
const schemas = require('./views/lib/schemas');

// Mapping from URL slug → mutator class name. (slugs plural → singular capitalized.)
const CRUD_SLUG_TO_NAME = {
  vendors:     'Vendor',
  locations:   'Location',
  categories:  'Category',
  users:       'User',
  assignments: 'Assignment',
  maintenance: 'Maintenance',
  licenses:    'License',
  departments: 'Department',
  approvals:   'Approval',
};

// Permission prefix per slug for the CRUD loop
const CRUD_PERM_PREFIX = {
  vendors:     'directory',
  locations:   'directory',
  categories:  'directory',
  users:       'directory',
  departments: 'directory',
  assignments: 'lifecycle',
  maintenance: 'lifecycle',
  approvals:   'lifecycle',
  licenses:    'inventory',
};

// Parent sidebar section per slug — used for the breadcrumb on new/edit/detail views.
const CRUD_PARENT = {
  vendors:     'Directory',
  locations:   'Directory',
  categories:  'Directory',
  users:       'Directory',
  assignments: 'Lifecycle',
  maintenance: 'Lifecycle',
  licenses:    'Inventory',
  departments: 'Directory',
  approvals:   'Lifecycle',
};

// Source rows for select-fk fields. Resolved once per request.
async function getSources(_slug) {
  const [categories, locations, vendors, users, assets, departments] = await Promise.all([
    prismaData.getCategories(),
    prismaData.getLocations(),
    prismaData.getVendors(),
    prismaData.getUsers(),
    prismaData.getAssetsFlat(),
    typeof prismaData.listDepartments === 'function' ? prismaData.listDepartments() : Promise.resolve([]),
  ]);
  return {
    categories,
    locations,
    vendors,
    users,
    assets: assets.map(a => ({ id: a.id, name: a.assetTag + ' — ' + a.name, assetTag: a.assetTag })),
    departments,
  };
}

// Build the locals object that a list page needs. Used by the CRUD loop when
// a modal submit fails validation — instead of rendering the standalone /new
// or /edit page, we re-render the list page with the modal pre-opened.
async function getListLocals(slug, query) {
  const sources = await getSources(slug);
  const base = { slug, query, schema: schemas[slug] || [], sources, title: TITLES[slug] || slug };
  switch (slug) {
    case 'vendors': {
      let rows = await prismaData.getVendors();
      const s = (query && query.search) || '';
      const st = (query && query.status) || '';
      if (s) { const q = s.toLowerCase(); rows = rows.filter(v => v.name.toLowerCase().includes(q) || (v.contactPerson || '').toLowerCase().includes(q) || (v.email || '').toLowerCase().includes(q)); }
      if (st) rows = rows.filter(v => v.status === st);
      return Object.assign({}, base, { vendors: rows, statusOptions: ['', 'ACTIVE', 'INACTIVE'] });
    }
    case 'locations': {
      let rows = await prismaData.getLocations();
      const s = (query && query.search) || '';
      if (s) { const q = s.toLowerCase(); rows = rows.filter(l => l.name.toLowerCase().includes(q) || (l.address || '').toLowerCase().includes(q)); }
      return Object.assign({}, base, { locations: rows });
    }
    case 'categories': {
      let rows = await prismaData.getCategories();
      const s = (query && query.search) || '';
      const t = (query && query.status) || '';
      if (s) { const q = s.toLowerCase(); rows = rows.filter(c => c.name.toLowerCase().includes(q)); }
      if (t) rows = rows.filter(c => c.type === t);
      return Object.assign({}, base, { categories: rows, statusOptions: ['', 'HARDWARE', 'SOFTWARE', 'PERIPHERAL', 'ACCESSORY'] });
    }
    case 'users': {
      let rows = await prismaData.getUsers();
      const s = (query && query.search) || '';
      const r = (query && query.status) || '';
      if (s) { const q = s.toLowerCase(); rows = rows.filter(u => u.fullName.toLowerCase().includes(q) || u.email.toLowerCase().includes(q)); }
      if (r) rows = rows.filter(u => u.role === r);
      return Object.assign({}, base, { users: rows, statusOptions: ['', 'IT_MANAGER', 'IT_SUPPORT', 'DEPARTMENT_HEAD', 'EMPLOYEE'] });
    }
    case 'assignments': {
      let rows = await prismaData.getAssignments();
      const s = (query && query.search) || '';
      if (s) { const q = s.toLowerCase(); rows = rows.filter(a => (a.assetId || '').toLowerCase().includes(q) || (a.user && a.user.fullName || '').toLowerCase().includes(q)); }
      return Object.assign({}, base, { assignments: rows });
    }
    case 'departments': {
      let rows = typeof prismaData.listDepartments === 'function' ? await prismaData.listDepartments() : [];
      const s = (query && query.search) || '';
      if (s) { const q = s.toLowerCase(); rows = rows.filter(d => d.name.toLowerCase().includes(q) || (d.code || '').toLowerCase().includes(q)); }
      return Object.assign({}, base, { departments: rows });
    }
    case 'approvals': {
      let rows = typeof prismaData.listApprovals === 'function' ? await prismaData.listApprovals() : [];
      const s = (query && query.search) || '';
      const st = (query && query.status) || '';
      if (s) { const q = s.toLowerCase(); rows = rows.filter(a => (a.entityType || '').toLowerCase().includes(q) || (a.entityId || '').toLowerCase().includes(q)); }
      if (st) rows = rows.filter(a => a.status === st);
      return Object.assign({}, base, { approvals: rows, statusOptions: ['', 'PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'] });
    }
    default: return Object.assign({}, base, {});
  }
}

for (const slug of Object.keys(CRUD_SLUG_TO_NAME)) {
  const Cap     = CRUD_SLUG_TO_NAME[slug];
  const capLc   = Cap[0].toLowerCase() + Cap.slice(1);
  const schema  = (schemas[slug]) || [];
  const hasCrud = typeof prismaData['create' + Cap] === 'function';
  const perm    = CRUD_PERM_PREFIX[slug] || 'assets'; // read/write permission prefix

  if (!hasCrud) continue;

  // GET /<slug>/:id  (detail)
  app.get('/' + slug + '/:id', requireAuth, can(perm + ':read'), async function(req, res, next) {
    const row = await prismaData['get' + Cap + 'ById'](req.params.id);
    if (!row) return next();
    res.render('pages/' + slug + '/detail', {
      title: row.name || row.fullName || capLc + ' ' + req.params.id,
      slug, schema, row, sources: await getSources(slug),
      capLc, cap: Cap,
      parentCrumb: CRUD_PARENT[slug] || 'IT Inventory',
      errors: {},
    });
  });

  // GET /<slug>/new
  app.get('/' + slug + '/new', requireAuth, can(perm + ':write'), async function(req, res) {
    res.render('pages/' + slug + '/new', {
      title:   'New ' + Cap,
      slug, schema,
      row:     {},
      sources: await getSources(slug),
      errors:  {},
      capLc,  cap: Cap,
      parentCrumb: CRUD_PARENT[slug] || 'IT Inventory',
    });
  });

  // POST /<slug>  (create)
  app.post('/' + slug, requireAuth, can(perm + ':write'), async function(req, res) {
    const result = await prismaData['create' + Cap](req.body || {});
    if (!result.success) {
      if (req.body._modal) {
        // Modal submit failed — re-render the list page with modal pre-opened
        const listLocals = await getListLocals(slug, {});
        return res.status(400).render('pages/' + slug + '/index', Object.assign({}, listLocals, {
          capLc, cap: Cap,
          parentCrumb: CRUD_PARENT[slug] || 'IT Inventory',
          modalErrors: result.errors,
          modalRow: req.body || {},
          modalMode: 'new',
        }));
      }
      return res.status(400).render('pages/' + slug + '/new', {
        title: 'New ' + Cap, slug, schema,
        row: req.body || {}, sources: await getSources(slug),
        errors: result.errors,
        capLc, cap: Cap,
        parentCrumb: CRUD_PARENT[slug] || 'IT Inventory',
      });
    }
    res.redirect('/' + slug + (req.body._modal ? '' : (result.data && result.data.id ? '/' + result.data.id : '')));
  });

  // GET /<slug>/:id/edit
  app.get('/' + slug + '/:id/edit', requireAuth, can(perm + ':write'), async function(req, res, next) {
    const row = await prismaData['get' + Cap + 'ById'](req.params.id);
    if (!row) return next();
    res.render('pages/' + slug + '/edit', {
      title:   'Edit ' + (row.name || row.fullName || capLc + ' ' + req.params.id),
      slug, schema,
      row, sources: await getSources(slug),
      errors:  {},
      capLc, cap: Cap,
      parentCrumb: CRUD_PARENT[slug] || 'IT Inventory',
    });
  });

  // POST /<slug>/:id  (update)
  app.post('/' + slug + '/:id', requireAuth, can(perm + ':write'), async function(req, res, next) {
    const existing = await prismaData['get' + Cap + 'ById'](req.params.id);
    if (!existing) return next();
    const result = await prismaData['update' + Cap](req.params.id, req.body || {});
    if (!result.success) {
      if (req.body._modal) {
        const listLocals = await getListLocals(slug, {});
        return res.status(400).render('pages/' + slug + '/index', Object.assign({}, listLocals, {
          capLc, cap: Cap,
          parentCrumb: CRUD_PARENT[slug] || 'IT Inventory',
          modalErrors: result.errors,
          modalRow: Object.assign({}, existing, req.body || {}),
          modalMode: 'edit',
        }));
      }
      return res.status(400).render('pages/' + slug + '/edit', {
        title: 'Edit ' + (existing.name || existing.fullName || req.params.id),
        slug, schema,
        row: Object.assign({}, existing, req.body || {}),
        sources: await getSources(slug),
        errors: result.errors,
        capLc, cap: Cap,
        parentCrumb: CRUD_PARENT[slug] || 'IT Inventory',
      });
    }
    res.redirect('/' + slug + '/' + req.params.id);
  });

  // POST /<slug>/:id/delete
  app.post('/' + slug + '/:id/delete', requireAuth, can(perm + ':write'), async function(req, res) {
    const result = await prismaData['delete' + Cap](req.params.id);
    if (result.success) return res.redirect('/' + slug);
    // delete failed — re-render the detail page with the FK blocker surfaced
    const row = await prismaData['get' + Cap + 'ById'](req.params.id) || { id: req.params.id };
    res.status(400).render('pages/' + slug + '/detail', {
      title: row.name || row.fullName || capLc + ' ' + req.params.id,
      slug, schema,
      row, sources: await getSources(slug),
      errors: result.errors,
      capLc, cap: Cap,
      parentCrumb: CRUD_PARENT[slug] || 'IT Inventory',
    });
  });
}

// ----------------------------------------------------------------------
// Static assets — locked-down allowlist.
// Previously this was `app.use(express.static(ROOT_DIR, ...))` which
// served the WHOLE project root. That leaked:
//   - /prisma/schema.prisma + /prisma/seed.js (the seed contains bcrypt
//     hashes of every demo account's password — credential disclosure)
//   - /server.js (full Express routing code)
//   - /views/lib/*.js (e.g. prismaData.js — exposes DB query patterns
//     and DB role names like 'c13-tech', so an attacker could fingerprint
//     staging/prod internals)
//   - /package.json + /package-lock.json (deps + start scripts)
//   - /tmp/, /ref/, /scripts/ (working + reference HTML)
//   - any future file dropped into the project root that nobody hand-
//     denied.
// New policy:
//   1. Explicit denylist enforced FIRST — belt-and-suspenders so even if
//      someone widens the static list later, these paths cannot leak.
//   2. Three explicit allowlisted mounts only — /assets, the local
//      mirror of /fonts.googleapis.com/css2, and /fonts.gstatic.com/*
//      IBM Plex Sans WOFF2. Anything else falls through to the 404.
// ----------------------------------------------------------------------

// Defense-in-depth denylist. The mounts below already exclude these paths,
// but an explicit regex stops a future maintainer from re-exposing source
// / secrets by mistake.
const STATIC_DENYLIST = /^\/(?:prisma|views|scripts|server\.js|package\.json|package-lock\.json|\.env|tmp|ref)(?:\/.*)?$/i;
app.use((req, res, next) => {
  if (STATIC_DENYLIST.test(req.path)) {
    // Return a plain 404 (not 403) so unauthenticated probing doesn't
    // confirm the URL exists.
    return res.status(404).end();
  }
  next();
});

// Explicit allowlist — the ONLY paths static middleware will serve.
//   /assets/*                 — CSS, JS, fonts, images used by the UI
//   /fonts.googleapis.com/*   — local mirror of the Google Fonts stylesheet
//   /fonts.gstatic.com/*      — local mirror of the IBM Plex Sans WOFF2
// Anything outside these prefixes is a 404 → falls through to the final
// 404 handler below.
app.use('/assets',             express.static(path.join(ROOT_DIR, 'assets'),             { index: false, extensions: false }));
app.use('/fonts.googleapis.com', express.static(path.join(ROOT_DIR, 'fonts.googleapis.com'), { index: false, extensions: false }));
app.use('/fonts.gstatic.com',  express.static(path.join(ROOT_DIR, 'fonts.gstatic.com'),  { index: false, extensions: false }));

// Final fallback: render the 404 EJS view with a 404 status.
app.use((_req, res) => {
  res.status(404).render('pages/pages-404', { title: TITLES['pages-404'] || '404' });
});

// Try to bind to PORT; if it's busy (EADDRINUSE), increment the port and retry.
// Prevents nodemon from crash-looping when 3000 is held by another app.
function listenWithFallback(app, startPort, host, maxAttempts) {
  return new Promise((resolve, reject) => {
    let port = startPort;
    let attempts = 0;

    const tryOnce = () => {
      const server = app.listen(port, host);

      server.once('listening', () => {
        resolve({ server, port, attempts });
      });

      server.once('error', (err) => {
        if (err.code === 'EADDRINUSE' && attempts < maxAttempts) {
          attempts += 1;
          console.warn(`[server] Port ${port} is in use, trying ${port + 1}...`);
          port += 1;
          setImmediate(tryOnce);
        } else {
          reject(err);
        }
      });
    };

    tryOnce();
  });
}

listenWithFallback(app, PORT, HOST, MAX_PORT_ATTEMPTS)
  .then(({ server, port, attempts }) => {
    if (attempts > 0) {
      console.log(`[server] Bound after ${attempts} retry(ies).`);
    }
    console.log(`\nClarity server running at http://${HOST}:${port}`);
    console.log(`Dashboard:  http://${HOST}:${port}/`);
    console.log(`Login page: http://${HOST}:${port}/auth-login.html`);
    console.log('Press Ctrl+C to stop.\n');

    // Graceful shutdown — drain in-flight HTTP requests, then disconnect
    // the Prisma client so its connection pool is released back to Postgres.
    // Without this, every Ctrl+C / nodemon restart / pkill silently leaks
    // open connections until Postgres reaps them — quickly exhausting
    // max_connections during dev/test churn (the classic
    // "FATAL: sorry, too many clients already" symptom).
    const shutdown = async (signal) => {
      console.log(`\n[server] Received ${signal}, shutting down...`);
      server.close(async (err) => {
        if (err) console.error('[server] Error during server.close():', err.message);
        try {
          await prisma.$disconnect();
          console.log('[server] Prisma disconnected, exiting cleanly.');
        } catch (e) {
          console.error('[server] Error disconnecting Prisma:', e.message);
        }
        process.exit(0);
      });
      // If a hung request prevents `server.close()` from firing, force-exit
      // but FIRST try a best-effort $disconnect so we don't leak sockets —
      // this is the exact path the original bug exposed.
      setTimeout(() => {
        console.warn('[server] Graceful shutdown timed out, forcing exit.');
        prisma.$disconnect()
          .catch((e) => console.error('[server] Force-exit disconnect failed:', e.message))
          .finally(() => process.exit(1));
      }, 5000).unref();
    };
    process.on('SIGINT',  () => shutdown('SIGINT'));
    process.on('SIGTERM', () => shutdown('SIGTERM'));

    // Last-resort safety nets — if Node crashes (uncaught throw or
    // unhandled rejection), still disconnect Prisma so we never leak DB
    // sockets, even on the unhappy path.
    process.on('uncaughtException', async (err) => {
      console.error('[server] Uncaught exception:', err);
      try { await prisma.$disconnect(); } catch (e) { console.error('[server] Disconnect after exception failed:', e.message); }
      process.exit(1);
    });
    process.on('unhandledRejection', async (reason) => {
      console.error('[server] Unhandled rejection:', reason);
      try { await prisma.$disconnect(); } catch (e) { console.error('[server] Disconnect after rejection failed:', e.message); }
      process.exit(1);
    });
  })
  .catch((err) => {
    console.error(`\n[server] Failed to start: ${err.message}`);
    if (err.code === 'EADDRINUSE') {
      console.error(
        `[server] Tried ports ${PORT}..${PORT + MAX_PORT_ATTEMPTS - 1} — all in use.\n` +
        `        Free one up, or pick a different range, e.g.:\n` +
        `          PORT=4000 npm start`
      );
    }
    process.exit(1);
  });
