// Express + EJS server for the IT Inventory dashboard.
// - EJS views live in views/pages/ and share partials from views/partials/
//   (head, topbar, sidebar, footer, scripts, scripts-auth).
// - Static assets (assets/, fonts.*/, _DataURI/, docs/, prisma/, etc.) are
//   served from the project root.
//
// Usage:
//   npm start        # production-style, no auto-reload
//   npm run dev      # nodemon watches this file and the static assets
//
// Then open http://127.0.0.1:3000/

const fs = require('fs');
const path = require('path');
const express = require('express');
const session = require('express-session');
const bcrypt = require('bcrypt');
const { PrismaClient } = require('@prisma/client');
// Single source of truth for the 5 builtins' permission sets.
// buildBuiltinKeyMap() transforms the human-readable Role.name keys
// (e.g. 'IT Manager') to UPPERCASE_UNDERSCORE keys (e.g. 'IT_MANAGER')
// so the map matches the session's userRole field. Defined in
// views/lib/permissions.js — the same module prisma/seed.js and
// views/lib/prismaData.js import CODES + BUILTINS + GROUPS from.
const { buildBuiltinKeyMap } = require('./views/lib/permissions');

const app = express();
const prisma = new PrismaClient();

// Body parsing for CRUD POSTs (form submissions).
app.use(express.urlencoded({ extended: true, limit: '1mb' }));

// Session middleware — memory store (dev only; swap to Redis/DB for production)
app.use(session({
  secret: process.env.SESSION_SECRET || 'inventory-dev-secret-change-in-production',
  resave: false,
  saveUninitialized: false,
  cookie: {
    httpOnly: true,
    secure: false, // set true behind HTTPS
    maxAge: 24 * 60 * 60 * 1000, // 24 hours
  },
}));

// Don't advertise the runtime in responses.
app.disable('x-powered-by');

// EJS view engine. The pages/ folder is the implicit root, so a page is
// rendered as res.render('pages/<name>').
app.set('view engine', 'ejs');
app.set('views', path.join(__dirname, 'views'));

// page-name -> human title map. Generated by scripts/convert-to-ejs.js so that
// the <title> tag in the head partial can show the right page name.
const TITLES = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'views', 'titles.json'), 'utf8')
);

const PORT = Number(process.env.PORT) || 3000;
const HOST = process.env.HOST || '127.0.0.1';
const MAX_PORT_ATTEMPTS = 10;
const ROOT_DIR = __dirname;

// Async error wrapper for Express 4.x — catches rejected promises in async
// route handlers and forwards them to the Express error handler.
const asyncHandler = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);

// Disable HTTP caching in dev so every refresh picks up the latest HTML/CSS/JS.
app.use((req, res, next) => {
  res.set('Cache-Control', 'no-store, no-cache, must-revalidate, proxy-revalidate');
  res.set('Pragma', 'no-cache');
  res.set('Expires', '0');
  next();
});

// Request log – one line per request, no extra dep.
app.use((req, _res, next) => {
  console.log(`[${new Date().toISOString()}] ${req.method} ${req.url}`);
  next();
});

// ----------------------------------------------------------------------
// EJS routes — must come BEFORE the static middleware so that .html URLs
// render the matching views/pages/<name>.ejs instead of the (now removed)
// root HTML files.
// ----------------------------------------------------------------------

// ----------------------------------------------------------------------
// Authentication routes — login, logout
// ----------------------------------------------------------------------

// GET /login — show login form (informational: if currently locked, render
// the 'too many attempts' banner so a refresh shows the user their status)
app.get('/login', (req, res) => {
  if (req.session.userId) return res.redirect('/');
  const guard = loginGuard.check(req.ip);
  res.render('pages/auth-login', {
    title:       'Login',
    error:       null,
    message:     null,
    lockedUntil: guard.allowed ? null : guard.endsAt.toISOString(),
  });
});

// POST /login — authenticate user (with IP-keyed rate-limit + hard lockout)
app.post('/login', async (req, res) => {
  // Pre-flight: don't even touch the DB or bcrypt if this IP is locked.
  // 429 means "real reject" so monitoring tools and clients can distinguish
  // it from generic 401s.
  const guard = loginGuard.check(req.ip);
  if (!guard.allowed) {
    return res.status(429).render('pages/auth-login', {
      title:       'Login',
      error:       null,
      message:     null,
      lockedUntil: guard.endsAt.toISOString(),
    });
  }
  const { email, password } = req.body || {};
  if (!email || !password) {
    // Missing-field attempts don't count as failed credentials — user
    // shouldn't be locked out for an HTML typo.
    return res.status(400).render('pages/auth-login', { title: 'Login', error: 'Email and password are required.', message: null });
  }
  try {
    // Find user by email across all tenants (email is unique per tenant via
    // tenantId_email compound key, so findFirst across tenants works at login).
    const user = await prisma.user.findFirst({
      where: { email },
      // Deep-include rolePermissions so the post-regenerate session can
      // be preloaded with the user's actual permission codes (DB-driven
      // RBAC). Without this `role.rolePermissions` would be undefined
      // and the session would get an empty permissions array, silently
      // locking the user out of every gated route until they re-login.
      include: { tenant: true, role: { include: { rolePermissions: { include: { permission: true } } } } },
    });
    // Combined invalid-because-no-user + invalid-because-bad-password path.
    // Avoids user-enumeration leaks. Either outcome counts as ONE failed
    // attempt against this IP.
    const valid = user ? await bcrypt.compare(password, user.passwordHash) : false;
    if (!user || !valid) {
      loginGuard.recordFail(req.ip);
      return res.status(401).render('pages/auth-login', { title: 'Login', error: 'Invalid email or password.', message: null });
    }
    // Update lastLoginAt — fire-and-forget so it doesn't delay the redirect
    prisma.user.update({ where: { id: user.id }, data: { lastLoginAt: new Date() } }).catch(() => {});
    // Regenerate session to prevent session fixation
    const redirectTo = req.session.returnTo || '/';
    req.session.regenerate(() => {
      req.session.userId   = user.id;
      req.session.tenantId = user.tenantId;
      req.session.tenantSlug = user.tenant ? user.tenant.slug : null;
      req.session.userName = user.fullName;
      req.session.userRole = user.role ? user.role.name.toUpperCase().replace(/ /g, '_') : null;
      // Preload the DB-driven perm codes so can(perm) can gate from
      // session without a per-request DB lookup. The deep include above
      // (role -> rolePermissions -> permission) is what populates this
      // array. Falls back to [] for users with no role or a role with
      // no permissions - can(perm) will then 403 every route, which is
      // the fail-safe behavior (no accidental privilege escalation).
      req.session.userPermissions = user.role && user.role.rolePermissions
        ? user.role.rolePermissions.map(rp => rp.permission.code)
        : [];
      // Successful login — clear the IP's bucket + counter + any lockout.
      loginGuard.clearOnSuccess(req.ip);
      res.redirect(redirectTo);
    });
  } catch (err) {
    console.error('Login error:', err);
    res.status(500).render('pages/auth-login', { title: 'Login', error: 'An error occurred. Please try again.', message: null });
  }
});

// GET /logout — destroy session and redirect to login
app.get('/logout', (req, res) => {
  req.session.destroy(() => {
    res.redirect('/login');
  });
});

// Auth guard middleware — redirects to /login if not authenticated.
// Saves the intended URL so the login handler can redirect back after success.
function requireAuth(req, res, next) {
  if (req.session && req.session.userId) return next();
  req.session.returnTo = req.originalUrl;
  res.redirect('/login');
}

// ----------------------------------------------------------------------
// Role-based access control (RBAC)
// ----------------------------------------------------------------------

// Permission list (13 codes, mirrors the CODES array in
// views/lib/permissions.js — the single source of truth):
//   assets:read / assets:write
//   lifecycle:read / lifecycle:write
//   directory:read / directory:write
//   inventory:read / inventory:write
//   admin:read / admin:write
//   communications:read / communications:write
//   dashboard:read
//
// BUILTIN_PERMISSIONS is the FALLBACK for sessions that pre-date
// the DB-driven migration (commit landed with this PR). New sessions
// get `req.session.userPermissions` preloaded at login (see POST /login
// + POST /profile/password) and can(perm) reads that array first. The
// fallback only fires for in-flight sessions from before the migration
// that haven't been re-issued yet — they'll be re-issued on next page
// load since the session id stays the same but the userPermissions
// field gets written on the next request that hits POST /login.
//
// Source of truth: views/lib/permissions.js → BUILTINS (human-readable
// keys) → buildBuiltinKeyMap() (UPPERCASE_UNDERSCORE keys, matching
// the session's userRole field set by POST /login's
// `user.role.name.toUpperCase().replace(/ /g, '_')` transform). The
// same BUILTINS object is what prisma/seed.js writes into the
// role_permissions junction table.
const BUILTIN_PERMISSIONS = buildBuiltinKeyMap();

// Middleware factory — returns a middleware that checks the given permission.
// Must be placed after requireAuth (which ensures req.session.userRole exists).
//
// DB-driven (commit this PR): checks `req.session.userPermissions` first
// (preloaded at login by POST /login + POST /profile/password from the
// user's Role → RolePermission → Permission chain). Falls back to
// BUILTIN_PERMISSIONS[role] only for sessions that pre-date the
// migration and haven't been re-issued. This means custom roles
// created via /roles/new actually gate pages (the pre-migration
// behavior was a silent 403 on every page because the hardcoded const
// didn't know about them).
function can(permission) {
  return (req, res, next) => {
    const role = req.session.userRole;
    // SECURITY: distinguish "not set" (undefined) from "explicitly empty"
    // (a custom role with no permissions saved). The naive
    // `userPermissions || BUILTIN[...]` chain would silently grant the
    // builtins' perms to a user whose zero-perm custom role should 403
    // everything. hasOwnProperty gates the fallback so an explicit []
    // stays an explicit [].
    const allowed = req.session.hasOwnProperty('userPermissions')
      ? req.session.userPermissions
      : (BUILTIN_PERMISSIONS[role] || []);
    if (!allowed.includes(permission)) {
      return res.status(403).render('pages/pages-404', {
        title: 'Access Denied',
        errorMessage: 'You do not have permission to access this page.',
      });
    }
    next();
  };
}

// Permission look-up for the wildcard .html route — maps page name to required
// permission so the bypass route can't skirt RBAC.
const PAGE_PERMISSIONS = {
  index:           null,            // dashboard — auth-only
  assets:         'assets:read',
  vendors:        'directory:read',
  locations:      'directory:read',
  categories:     'directory:read',
  users:          'directory:read',
  assignments:    'lifecycle:read',
  maintenance:    'lifecycle:read',
  licenses:       'inventory:read',
  departments:    'directory:read',
  approvals:      'lifecycle:read',
  'license-seats': 'inventory:read',
  warranty:       'lifecycle:read',
  roles:          'admin:read',
  'audit-log':    'admin:read',
  reports:        'admin:read',
  notifications:  'communications:read',
  webhooks:       'communications:read',
  profile:         null,            // profile — auth-only
};

// Layout locals for all rendered pages — inject user info + permissions
app.use((req, res, next) => {
  const role = req.session.userRole;
  res.locals.currentUser = req.session.userId ? {
    id: req.session.userId,
    fullName: req.session.userName,
    role: role,
    tenantSlug: req.session.tenantSlug,
  } : null;
  res.locals.userPermissions = req.session.hasOwnProperty('userPermissions')
    ? req.session.userPermissions
    : (role ? (BUILTIN_PERMISSIONS[role] || []) : []);
  next();
});

// Set request context for prismaData.js tenant resolution
app.use((req, _res, next) => {
  prismaData.setRequest(req);
  next();
});

// Profile page — all authenticated users can see their own profile
app.get('/profile', requireAuth, async (req, res) => {
  res.render('pages/profile', {
    title:   'My Profile',
    success: null,
    error:   null,
  });
});

// POST /profile/password — change password
app.post('/profile/password', requireAuth, async (req, res) => {
  const { currentPassword, newPassword, confirmPassword } = req.body || {};
  // Validation
  if (!currentPassword || !newPassword || !confirmPassword) {
    return res.status(400).render('pages/profile', {
      title:   'My Profile',
      success: null,
      error:   'All fields are required.',
    });
  }
  if (newPassword.length < 6) {
    return res.status(400).render('pages/profile', {
      title:   'My Profile',
      success: null,
      error:   'New password must be at least 6 characters.',
    });
  }
  if (newPassword !== confirmPassword) {
    return res.status(400).render('pages/profile', {
      title:   'My Profile',
      success: null,
      error:   'New password and confirmation do not match.',
    });
  }
  try {
    // Look up user and verify current password. We MUST `include` the
    // tenant + role relations so the post-regenerate session can be
    // re-populated with tenantSlug + userRole (the same fields
    // POST /login sets) -- otherwise the new session loses tenant
    // context and silently breaks permission gates + audit-log
    // attribution below.
    const user = await prisma.user.findUnique({
      where: { id: req.session.userId },
      // Deep-include rolePermissions so the post-regenerate session can
      // be re-populated with the user's actual permission codes (see
      // the parallel comment in POST /login). The captured-from-user
      // value is then assigned inside the regenerate callback below
      // (postChangeUserPerms) so the fresh session has the same
      // permission set as the old one - otherwise password change
      // would silently lock the user out of every gated route.
      include: { tenant: true, role: { include: { rolePermissions: { include: { permission: true } } } } },
    });
    if (!user) {
      return res.status(400).render('pages/profile', {
        title:   'My Profile',
        success: null,
        error:   'User not found.',
      });
    }
    const valid = await bcrypt.compare(currentPassword, user.passwordHash);
    if (!valid) {
      return res.status(400).render('pages/profile', {
        title:   'My Profile',
        success: null,
        error:   'Current password is incorrect.',
      });
    }
    if (currentPassword === newPassword) {
      return res.status(400).render('pages/profile', {
        title:   'My Profile',
        success: null,
        error:   'New password must be different from current password.',
      });
    }
    // SECURITY (commit b30ee7a followup): capture the session fields
    // into local variables BEFORE regenerate. After regenerate runs,
    // `req.session` is a FRESH empty session - any read on
    // `req.session.tenantSlug` or `req.session.userRole` would return
    // undefined and silently break the user's permission gates
    // (can('dashboard:read') etc.) and audit-log attribution for the
    // post-password-change session. Pre-fix the handler copy-pasted
    // these from `req.session` (the new empty session) and the user
    // would land on /profile with a session that had userId + tenantId
    // but no tenantSlug + userRole. We now read them straight off
    // `user` (with `tenant` + `role` included above) to match the
    // POST /login capture shape exactly.
    const postChangeTenantId   = user.tenantId;
    const postChangeTenantSlug = user.tenant ? user.tenant.slug : null;
    const postChangeUserName   = user.fullName;
    const postChangeUserRole   = user.role  ? user.role.name.toUpperCase().replace(/ /g, '_') : null;
    // Preload the perm codes BEFORE regenerate (same pattern as
    // postChangeUserRole above) so the fresh session can re-apply
    // them via req.session.userPermissions. Without this capture, the
    // user would land on /profile with a session that has userId +
    // tenantId + userRole but no userPermissions, and can(perm) would
    // 403 every gated page they visited.
    const postChangeUserPerms  = user.role && user.role.rolePermissions
      ? user.role.rolePermissions.map(rp => rp.permission.code)
      : [];
    // Hash new password, update, and regenerate session for security
    const hash = await bcrypt.hash(newPassword, 12);
    await prisma.user.update({ where: { id: user.id }, data: { passwordHash: hash } });
    req.session.regenerate(() => {
      req.session.userId     = user.id;
      req.session.tenantId   = postChangeTenantId;
      req.session.tenantSlug = postChangeTenantSlug;
      req.session.userName   = postChangeUserName;
      req.session.userRole   = postChangeUserRole;
      req.session.userPermissions = postChangeUserPerms;
      res.render('pages/profile', {
        title:   'My Profile',
        success: 'Password changed successfully.',
        error:   null,
      });
    });
  } catch (err) {
    console.error('Password change error:', err);
    res.status(500).render('pages/profile', {
      title:   'My Profile',
      success: null,
      error:   'An error occurred. Please try again.',
    });
  }
});

// Root — dashboard with a permission gate. Users WITH 'dashboard:read'
// (IT_MANAGER, IT_SUPPORT) see the full tenant-aggregate dashboard.
// Everyone else is redirected to /assets — the lowest-tier page every
// role has assets:read for. The gate matches the two /api/dashboard/*
// endpoints below so the UI can never silently succeed (empty chart)
// OR fail (403 toast) with data the user's role shouldn't see.
app.get('/', requireAuth, async (req, res) => {
  const allowed = req.session.hasOwnProperty('userPermissions')
    ? req.session.userPermissions
    : (BUILTIN_PERMISSIONS[req.session.userRole] || []);
  if (!allowed.includes('dashboard:read')) {
    return res.redirect('/assets');
  }
  res.render('pages/index', {
    title: TITLES['index'] || 'Dashboard',
    pageScripts: ['assets/libs/apexcharts/apexcharts.min.js', 'assets/js/pages/dashboard.init.js'],
  });
});

// ----------------------------------------------------------------------
// JSON API helper. Centralises the (requireAuth + can(...)) gate so
// every /api/* endpoint below is RBAC-enforced by construction — a new
// JSON route is a one-liner via apiRoute(method, slug, subPath, perm,
// handler). Direct app.get/app.post(...) calls with paths starting
// /api/ are forbidden by convention; reviewers should reject additions
// that bypass this gate.
//   method      — 'get'|'post'|'put'|'patch'|'delete'
//   slug        — namespace (sidebar CRUD slug OR dedicated JSON slug)
//   subPath     — optional URL tail (default '')
//   permSuffix  — 'read'|'write' (gate is `<slug>:<permSuffix>`)
//   handler     — async (req, res, next) => ...
// ----------------------------------------------------------------------
function apiRoute(method, slug, subPath, permSuffix, handler) {
  const path = '/api/' + slug + (subPath || '');
  app[method](path, requireAuth, can(slug + ':' + permSuffix), handler);
}

// API — dashboard statistics (used by the ApexCharts dashboard.init.js)
apiRoute('get', 'dashboard', '/stats', 'read', async (_req, res) => {
  try {
    const tid = _req.session.tenantId;
    const [
      allAssets,
      totalUsers,
      totalVendors,
      totalLocations,
      recentAudit,
    ] = await Promise.all([
      prisma.asset.findMany({ where: { tenantId: tid }, select: { status: true, categoryId: true } }),
      prisma.user.count({ where: { tenantId: tid } }),
      prisma.vendor.count({ where: { tenantId: tid } }),
      prisma.location.count({ where: { tenantId: tid } }),
      prisma.auditLog.findMany({ where: { tenantId: tid }, include: { user: true }, orderBy: { createdAt: 'desc' }, take: 10 }),
    ]);

    // Group by status in JS
    const statusMap = {};
    allAssets.forEach(a => {
      statusMap[a.status] = (statusMap[a.status] || 0) + 1;
    });
    const assetsByStatus = Object.entries(statusMap).map(([status, count]) => ({ status, count }));

    // Group by category in JS
    const catMap = {};
    allAssets.forEach(a => {
      if (a.categoryId) catMap[a.categoryId] = (catMap[a.categoryId] || 0) + 1;
    });
    // Resolve category names
    const categoryIds = Object.keys(catMap);
    const categories = categoryIds.length
      ? await prisma.category.findMany({ where: { id: { in: categoryIds } } })
      : [];
    const nameMap = {};
    categories.forEach(c => { nameMap[c.id] = c.name; });
    const assetsByCategory = Object.entries(catMap)
      .map(([catId, count]) => ({ category: nameMap[catId] || 'Uncategorized', count }))
      .sort((a, b) => b.count - a.count)
      .slice(0, 8);

    res.json({
      totalAssets: allAssets.length,
      assetsByStatus,
      assetsByCategory,
      totalUsers,
      totalVendors,
      totalLocations,
      recentActivity: recentAudit.map(e => ({
        action: e.action,
        entityType: e.entityType,
        entityId: e.entityId,
        userName: e.user ? e.user.fullName : 'System',
        createdAt: e.createdAt,
      })),
    });
  } catch (err) {
    console.error('Dashboard stats error:', err);
    res.status(500).json({ error: 'Failed to load dashboard statistics.' });
  }
});

// API — dashboard 7-day trends (sparkline data for the stat cards).
//   Returns counts per day for the last 7 days (oldest -> newest).
//   Each metric is numerically aligned with the `labels` array so the
//   client can render Apache-style sparklines without re-pivoting.
apiRoute('get', 'dashboard', '/trends', 'read', async (_req, res) => {
  try {
    const tid = _req.session.tenantId;
    const DAYS = 7;
    // Build the 7 day-buckets (midnight..midnight) ending today, oldest first.
    const now = new Date();
    const startOfToday = new Date(now.getFullYear(), now.getMonth(), now.getDate());
    const buckets = [];
    for (let i = DAYS - 1; i >= 0; i--) {
      const d = new Date(startOfToday);
      d.setDate(d.getDate() - i);
      buckets.push(d);
    }
    const from = buckets[0];
    const labels = buckets.map(d => d.toISOString().slice(0, 10));
    const inWindow = { createdAt: { gte: from } };

    const [assetsRaw, usersRaw, assignmentsRaw, vendorsRaw] = await Promise.all([
      prisma.asset.findMany({ where: { tenantId: tid, ...inWindow }, select: { createdAt: true } }),
      prisma.user.findMany({ where: { tenantId: tid, ...inWindow }, select: { createdAt: true } }),
      // SECURITY/CORRECTNESS: filter assignments by `assignedAt` (the
      // business-meaningful date) not `createdAt` (the row-creation
      // date). The shared `inWindow` filter is `createdAt >= from`,
      // which would silently drop any assignment whose row was created
      // in the last 7 days but was assigned earlier (and would also
      // pick up old assignments that just happened to be re-saved).
      // The sparkline then bucketises by `assignedAt`, so the WHERE
      // and the GROUP BY must agree on which date they're using.
      prisma.assignment.findMany({ where: { tenantId: tid, assignedAt: { gte: from } }, select: { assignedAt: true } }),
      prisma.vendor.findMany({ where: { tenantId: tid, ...inWindow }, select: { createdAt: true } }),
    ]);

    // Bucket-by-day helper. Counts rows whose date falls in [buckets[i], buckets[i+1]).
    function bucketize(records, getDate) {
      const counts = new Array(DAYS).fill(0);
      for (const r of records) {
        const d = getDate(r);
        if (!d) continue;
        const t = d.getTime();
        for (let i = 0; i < DAYS; i++) {
          const lo = buckets[i].getTime();
          const hi = i + 1 < DAYS ? buckets[i + 1].getTime() : startOfToday.getTime() + 24 * 60 * 60 * 1000;
          if (t >= lo && t < hi) { counts[i]++; break; }
        }
      }
      return counts;
    }

    res.json({
      labels,
      assets:       bucketize(assetsRaw, r => r.createdAt),
      users:        bucketize(usersRaw, r => r.createdAt),
      assignments:  bucketize(assignmentsRaw, r => r.assignedAt),
      vendors:      bucketize(vendorsRaw, r => r.createdAt),
    });
  } catch (err) {
    console.error('Dashboard trends error:', err);
    res.status(500).json({ error: 'Failed to load dashboard trends.' });
  }
});

// Error pages — set the right HTTP status before rendering the template.
app.get('/pages-404.html', (_req, res) => {
  res.status(404).render('pages/pages-404', { title: TITLES['pages-404'] || '404' });
});
app.get('/pages-500.html', (_req, res) => {
  res.status(500).render('pages/pages-500', { title: TITLES['pages-500'] || '500' });
});

// All other *.html URLs → render the matching EJS view.
// Only unauthenticated pages that are safe to serve without auth:
// auth-*, pages-4*, pages-5*
const PUBLIC_PAGES = /^(auth|pages-4|pages-5)/;
app.get('/:page.html', (req, res, next) => {
  const page = req.params.page;
  // Defensive: only allow simple, single-segment page names. This blocks any
  // attempt to escape views/pages/ (e.g. via ".." or path tricks) and ensures
  // we only ever render files we actually generated from the Clarity template (originally a Minia fork).
  if (!/^[a-zA-Z0-9_-]+$/.test(page)) return next();
  // Require auth for all non-public pages (blocks /assets.html, /vendors.html, etc.)
  if (!PUBLIC_PAGES.test(page) && (!req.session || !req.session.userId)) {
    req.session.returnTo = req.originalUrl;
    return res.redirect('/login');
  }
  // Check RBAC for non-public pages that match a known permission
  if (!PUBLIC_PAGES.test(page) && PAGE_PERMISSIONS.hasOwnProperty(page)) {
    const required = PAGE_PERMISSIONS[page];
    if (required) {
      const role = req.session.userRole;
      // Same hasOwnProperty-gated fallback as the can() middleware so
      // a custom role with zero perms doesn't silently re-elevate via
      // the builtins map.
      const allowed = req.session.hasOwnProperty('userPermissions')
        ? req.session.userPermissions
        : (BUILTIN_PERMISSIONS[role] || []);
      if (!allowed.includes(required)) {
        return res.status(403).render('pages/pages-404', {
          title: 'Access Denied',
          errorMessage: 'You do not have permission to access this page.',
        });
      }
    }
  }
  const viewPath = path.join(__dirname, 'views', 'pages', page + '.ejs');
  if (fs.existsSync(viewPath)) {
    res.render('pages/' + page, { title: TITLES[page] || page });
  } else {
    next(); // fall through to 404
  }
});

// ----------------------------------------------------------------------
// Asset routes (Phase 1 of the IT inventory UI). mockData.js returns objects
// shaped exactly like Prisma will return in Phase 6, so the route handlers
// can swap from `mockData.getAssets(...)` to `prisma.asset.findMany(...)`
// with no EJS changes.
// ----------------------------------------------------------------------
const prismaData = require('./views/lib/prismaData');
const loginGuard = require('./views/lib/loginGuard');

app.get('/assets', requireAuth, can('assets:read'), async (req, res) => {
  // SECURITY: roles without 'assets:write' (DEPARTMENT_HEAD, EMPLOYEE)
  // are server-side auto-scoped to their own ACTIVE assignments so the
  // landing page these users arrive at after the /api dashboard gate
  // redirects them doesn't dump the full tenant asset list. The scope
  // is enforced here, not via a query param — a low-perm user can't
  // opt out by editing the URL.
  const role = req.session.userRole;
  // Same hasOwnProperty-gated fallback as the can() middleware. Without
  // the gate, a user whose custom role was saved with zero permissions
  // would silently be re-elevated to the IT_MANAGER perm set and skip
  // the personal-asset scoping.
  const allowed = req.session.hasOwnProperty('userPermissions')
    ? req.session.userPermissions
    : (BUILTIN_PERMISSIONS[role] || []);
  const canWriteAssets = allowed.includes('assets:write');
  const scopedUserId = canWriteAssets ? undefined : req.session.userId;
  const result = await prismaData.getAssets({
    status:         req.query.status         || undefined,
    categoryId:     req.query.categoryId     || undefined,
    locationId:     req.query.locationId     || undefined,
    vendorId:       req.query.vendorId       || undefined,
    assignedOnly:   req.query.assignedOnly === '1',
    search:         req.query.search         || undefined,
    page:           Number(req.query.page)    || 1,
    assignedUserId: scopedUserId,
  });
  res.render('pages/assets/index', {
    title:           TITLES['assets'] || 'Assets',
    query:           req.query,
    result:          result,
    isPersonalScope: !canWriteAssets,
    // Both queries carry the SAME scope. When scoped, assetsAll.total
    // equals result.total so the "X of Y" hint vanishes automatically
    // (the existing view checks result.total !== assetsAll.total).
    // For admins, both are unscoped — the hint shows normally.
    assetsAll:       await prismaData.getAssets({ assignedUserId: scopedUserId }),
    categories:      await prismaData.getCategories(),
    locations:       await prismaData.getLocations(),
    vendors:         await prismaData.getVendors(),
  });
});

app.get('/assets/new', requireAuth, can('assets:write'), async (_req, res) => {
  res.render('pages/assets/new', {
    title:      TITLES['assets/new'] || 'New Asset',
    categories: await prismaData.getCategories(),
    vendors:    await prismaData.getVendors(),
    locations:  await prismaData.getLocations(),
  });
});

app.get('/assets/:id', requireAuth, can('assets:read'), async (req, res, next) => {
  const asset = await prismaData.getAssetById(req.params.id);
  if (!asset) return next();
  // SECURITY: roles without 'assets:write' (EMPLOYEE, DEPARTMENT_HEAD)
  // can only view assets CURRENTLY ASSIGNED to them. Anything else
  // gets the same 404 as a missing asset (via the final fallback),
  // so a logged-in low-perm user cannot probe tenant cuids from the
  // URL to leak vendor / purchase cost / warranty / assignment history.
  // 404 (not 403) deliberately - 403 would confirm the cuid exists.
  const role = req.session.userRole;
  // Same hasOwnProperty-gated fallback as the can() middleware. Without
  // the gate, a user whose custom role was saved with zero permissions
  // would silently be re-elevated to the IT_MANAGER perm set and bypass
  // the per-asset ownership check.
  const allowed = req.session.hasOwnProperty('userPermissions')
    ? req.session.userPermissions
    : (BUILTIN_PERMISSIONS[role] || []);
  const canWriteAssets = allowed.includes('assets:write');
  if (!canWriteAssets && asset.assignedTo?.id !== req.session.userId) return next();
  // SECURITY (defense-in-depth): getAssetById is already tenant-scoped
  // at the data layer (findFirst { id, tenantId: tid }). Explicit
  // row-level check below documents intent at the call-site - 404
  // is identical to "asset doesn't exist" or "wrong tenant" from the
  // attacker's perspective.
  if (asset.tenantId !== req.session.tenantId) return next();
  res.render('pages/assets/detail', {
    title:       asset.name,
    asset:       asset,
    assignments: await prismaData.getAssignmentsForAsset(asset.id),
    maintenance: await prismaData.getMaintenanceForAsset(asset.id),
    users:       await prismaData.getUsers(),
  });
});

app.get('/assets/:id/edit', requireAuth, can('assets:write'), async (req, res, next) => {
  const asset = await prismaData.getAssetById(req.params.id);
  if (!asset) return next();
  // SECURITY: belt-and-suspenders scope on /assets/:id/edit. The
  // can('assets:write') middleware above already 403s non-write roles,
  // but adding the same per-asset scope inside the handler keeps the
  // pattern uniform with /assets/:id and /assets/:id/qr so a future
  // maintainer can't be surprised by a non-write role ever reaching it.
  const role = req.session.userRole;
  // Same hasOwnProperty-gated fallback as the can() middleware. Without
  // the gate, a user whose custom role was saved with zero permissions
  // would silently be re-elevated to the IT_MANAGER perm set and bypass
  // the per-asset ownership check.
  const allowed = req.session.hasOwnProperty('userPermissions')
    ? req.session.userPermissions
    : (BUILTIN_PERMISSIONS[role] || []);
  const canWriteAssets = allowed.includes('assets:write');
  if (!canWriteAssets && asset.assignedTo?.id !== req.session.userId) return next();
  if (asset.tenantId !== req.session.tenantId) return next();
  res.render('pages/assets/edit', {
    title:      'Edit ' + asset.name,
    asset:      asset,
    categories: await prismaData.getCategories(),
    vendors:    await prismaData.getVendors(),
    locations:  await prismaData.getLocations(),
  });
});

app.get('/assets/:id/qr', requireAuth, can('assets:read'), async (req, res, next) => {
  const asset = await prismaData.getAssetById(req.params.id);
  if (!asset) return next();
  // SECURITY: roles without 'assets:write' (EMPLOYEE, DEPARTMENT_HEAD)
  // can only print QR for assets CURRENTLY ASSIGNED to them. Same
  // 404 treatment as /assets/:id so the QR page can't be used as a
  // cross-tenant asset enumerator either.
  const role = req.session.userRole;
  // Same hasOwnProperty-gated fallback as the can() middleware. Without
  // the gate, a user whose custom role was saved with zero permissions
  // would silently be re-elevated to the IT_MANAGER perm set and bypass
  // the per-asset ownership check.
  const allowed = req.session.hasOwnProperty('userPermissions')
    ? req.session.userPermissions
    : (BUILTIN_PERMISSIONS[role] || []);
  const canWriteAssets = allowed.includes('assets:write');
  if (!canWriteAssets && asset.assignedTo?.id !== req.session.userId) return next();
  if (asset.tenantId !== req.session.tenantId) return next();
  res.render('pages/assets/qr', {
    title: 'Print QR - ' + asset.name,
    asset: asset,
  });
});

// ----------------------------------------------------------------------
// Directory / lifecycle / inventory list pages (added for the new sidebar nav).
// Data-driven pages pass rows straight from mockData.js. Stub pages (licenses,
// departments, approvals) just render an empty-state banner — the views
// handle the "no data" branch themselves, so we don't need to inject empty
// arrays from the route.
// ----------------------------------------------------------------------

// Dedicated user detail route — defined before the CRUD loop so it takes
// precedence over the generic GET /users/:id handler. Shows enriched data.
app.get('/users/:id', requireAuth, can('directory:read'), async (req, res, next) => {
  const user = await prismaData.getUserDetail(req.params.id);
  if (!user) return next();
  // SECURITY (defense-in-depth): getUserDetail is already tenant-scoped
  // at the data layer. This explicit row-level check stops a future
  // data-layer loosening from re-introducing a cross-tenant user-detail
  // leak (e.g. /users/<foreign-tenant-user-id> rendering another tenant's
  // contact info / role / department).
  if (user.tenantId !== req.session.tenantId) return next();
  res.render('pages/users/detail', {
    title:       user.fullName,
    slug:        'users',
    row:         user,
    user:        user,
    schema:      schemas['users'] || [],
    sources:     await getSources('users'),
    parentCrumb: 'Directory',
    capLc:       'user',
    cap:         'User',
    errors:      {},
  });
});

// Directory — model-driven, mockData-backed
app.get('/vendors', requireAuth, can('directory:read'), async (req, res) => {
  let rows = await prismaData.getVendors();
  const search = req.query.search || '';
  const status = req.query.status || '';
  if (search) {
    const q = search.toLowerCase();
    rows = rows.filter(v =>
      v.name.toLowerCase().includes(q) ||
      (v.contactPerson || '').toLowerCase().includes(q) ||
      (v.email || '').toLowerCase().includes(q)
    );
  }
  if (status) {
    rows = rows.filter(v => v.status === status);
  }
  res.render('pages/vendors/index', {
    title:   'Vendors',
    slug:    'vendors',
    query:   req.query,
    vendors: rows,
    schema:  schemas['vendors'] || [],
    sources: await getSources('vendors'),
    statusOptions: ['', 'ACTIVE', 'INACTIVE'],
  });
});

app.get('/locations', requireAuth, can('directory:read'), async (req, res) => {
  let rows = await prismaData.getLocations();
  const search = req.query.search || '';
  if (search) {
    const q = search.toLowerCase();
    rows = rows.filter(l => l.name.toLowerCase().includes(q) || (l.address || '').toLowerCase().includes(q));
  }
  res.render('pages/locations/index', {
    title:     'Locations',
    slug:      'locations',
    query:     req.query,
    locations: rows,
    schema:    schemas['locations'] || [],
    sources:   await getSources('locations'),
  });
});

app.get('/categories', requireAuth, can('directory:read'), async (req, res) => {
  let rows = await prismaData.getCategories();
  const search = req.query.search || '';
  const type   = req.query.status || '';
  if (search) {
    const q = search.toLowerCase();
    rows = rows.filter(c => c.name.toLowerCase().includes(q));
  }
  if (type) rows = rows.filter(c => c.type === type);
  res.render('pages/categories/index', {
    title:         'Categories',
    slug:          'categories',
    query:         req.query,
    categories:    rows,
    schema:        schemas['categories'] || [],
    sources:       await getSources('categories'),
    statusOptions: ['', 'HARDWARE', 'SOFTWARE', 'PERIPHERAL', 'ACCESSORY'],
  });
});

app.get('/users', requireAuth, can('directory:read'), async (req, res) => {
  let rows = await prismaData.getUsers();
  const search = req.query.search || '';
  const role   = req.query.status || '';
  if (search) {
    const q = search.toLowerCase();
    rows = rows.filter(u => u.fullName.toLowerCase().includes(q) || u.email.toLowerCase().includes(q));
  }
  if (role) rows = rows.filter(u => u.role === role);
  res.render('pages/users/index', {
    title:         'Users',
    slug:          'users',
    query:         req.query,
    users:         rows,
    schema:        schemas['users'] || [],
    sources:       await getSources('users'),
    statusOptions: ['', 'IT_MANAGER', 'IT_SUPPORT', 'DEPARTMENT_HEAD', 'EMPLOYEE'],
  });
});

// Lifecycle — flat assignments + maintenance listings (added as global accessors to mockData)
app.get('/assignments', requireAuth, can('lifecycle:read'), async (req, res) => {
  let rows = await prismaData.getAssignments();
  const search = req.query.search || '';
  if (search) {
    const q = search.toLowerCase();
    rows = rows.filter(a =>
      (a.assetId || '').toLowerCase().includes(q) ||
      (a.user && a.user.fullName || '').toLowerCase().includes(q)
    );
  }
  res.render('pages/assignments/index', {
    title:       'Assignments',
    slug:        'assignments',
    query:       req.query,
    assignments: rows,
    schema:      schemas['assignments'] || [],
    sources:     await getSources('assignments'),
  });
});

app.get('/maintenance', requireAuth, can('lifecycle:read'), async (req, res) => {
  let rows = await prismaData.getMaintenance();
  const search = req.query.search || '';
  const status = req.query.status || '';
  if (search) {
    const q = search.toLowerCase();
    rows = rows.filter(m =>
      (m.description || '').toLowerCase().includes(q) ||
      (m.vendor && m.vendor.name || '').toLowerCase().includes(q) ||
      (m.ticketNumber || '').toLowerCase().includes(q)
    );
  }
  if (status) rows = rows.filter(m => m.status === status);
  res.render('pages/maintenance/index', {
    title:         'Maintenance',
    slug:          'maintenance',
    query:         req.query,
    maintenance:   rows,
    schema:        schemas['maintenance'] || [],
    statusOptions: ['', 'OPEN', 'IN_PROGRESS', 'COMPLETED', 'CLOSED'],
  });
});

// Inventory/Lifecycle stubs — Phase 6 (Prisma) wiring only; views render empty-state
// Pass an empty array so the toolbar + table-or-empty-state pattern works.
app.get('/licenses', requireAuth, can('inventory:read'), async (req, res) => {
  let rows = typeof prismaData.listLicenses === 'function' ? await prismaData.listLicenses() : [];
  const search = req.query.search || '';
  if (search) {
    const q = search.toLowerCase();
    rows = rows.filter(l => l.name.toLowerCase().includes(q) || (l.licenseKey || '').toLowerCase().includes(q));
  }
  res.render('pages/licenses/index', {
    title:    'Software Licenses',
    slug:     'licenses',
    query:    req.query,
    licenses: rows,
    schema:   schemas['licenses'] || [],
  });
});
app.get('/departments', requireAuth, can('directory:read'), async (req, res) => {
  let rows = typeof prismaData.listDepartments === 'function' ? await prismaData.listDepartments() : [];
  const search = req.query.search || '';
  if (search) {
    const q = search.toLowerCase();
    rows = rows.filter(d => d.name.toLowerCase().includes(q) || (d.code || '').toLowerCase().includes(q));
  }
  res.render('pages/departments/index', {
    title:       'Departments',
    slug:        'departments',
    query:       req.query,
    departments: rows,
    schema:      schemas['departments'] || [],
    sources:     await getSources('departments'),
  });
});
app.get('/approvals', requireAuth, can('lifecycle:read'), async (req, res) => {
  let rows = typeof prismaData.listApprovals === 'function' ? await prismaData.listApprovals() : [];
  const search = req.query.search || '';
  const status = req.query.status || '';
  if (search) {
    const q = search.toLowerCase();
    rows = rows.filter(a => (a.entityType || '').toLowerCase().includes(q) || (a.entityId || '').toLowerCase().includes(q));
  }
  if (status) rows = rows.filter(a => a.status === status);
  res.render('pages/approvals/index', {
    title:         'Approvals',
    slug:          'approvals',
    query:         req.query,
    approvals:     rows,
    schema:        schemas['approvals'] || [],
    sources:       await getSources('approvals'),
    statusOptions: ['', 'PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'],
  });
});

// ----------------------------------------------------------------------
// PRO sidebar pages — inventory, lifecycle, admin, communications.
// All render empty-state stubs wired for Phase 6 Prisma swap.
// ----------------------------------------------------------------------

app.get('/license-seats', requireAuth, can('inventory:read'), async (req, res) => {
  let rows = await prismaData.getLicenseSeats();
  const search = req.query.search || '';
  if (search) {
    const q = search.toLowerCase();
    rows = rows.filter(s =>
      (s.licenseName || '').toLowerCase().includes(q) ||
      (s.assetName || '').toLowerCase().includes(q) ||
      (s.userName || '').toLowerCase().includes(q)
    );
  }
  res.render('pages/license-seats/index', {
    title:  'License Seats',
    slug:   'license-seats',
    query:  req.query,
    seats:  rows,
    schema: schemas['license-seats'] || [],
  });
});

app.get('/warranty', requireAuth, can('lifecycle:read'), async (req, res) => {
  let rows = await prismaData.getWarranties();
  const search = req.query.search || '';
  const status = req.query.status || '';
  if (search) {
    const q = search.toLowerCase();
    rows = rows.filter(w =>
      (w.assetName || '').toLowerCase().includes(q) ||
      (w.assetTag || '').toLowerCase().includes(q)
    );
  }
  if (status) rows = rows.filter(w => w.status === status);
  res.render('pages/warranty/index', {
    title:         'Warranty Tracking',
    slug:          'warranty',
    query:         req.query,
    warranties:    rows,
    schema:        schemas['warranty'] || [],
    statusOptions: ['', 'ACTIVE', 'EXPIRING', 'EXPIRED'],
  });
});

app.get('/roles', requireAuth, can('admin:read'), async (req, res) => {
  let rows = await prismaData.getRoles();
  const search = req.query.search || '';
  if (search) {
    const q = search.toLowerCase();
    rows = rows.filter(r =>
      r.name.toLowerCase().includes(q) ||
      (r.description || '').toLowerCase().includes(q)
    );
  }
  res.render('pages/roles/index', {
    title:  'Roles & Permissions',
    slug:   'roles',
    query:  req.query,
    roles:  rows,
    schema: schemas['roles'] || [],
  });
});

app.get('/audit-log', requireAuth, can('admin:read'), async (req, res) => {
  let rows = await prismaData.getAuditLogs();
  const search = req.query.search || '';
  if (search) {
    const q = search.toLowerCase();
    rows = rows.filter(e =>
      (e.action || '').toLowerCase().includes(q) ||
      (e.entityType || '').toLowerCase().includes(q) ||
      (e.entityId || '').toLowerCase().includes(q) ||
      ((e.user && e.user.fullName) || '').toLowerCase().includes(q)
    );
  }
  res.render('pages/audit-log/index', {
    title:   'Audit Log',
    slug:    'audit-log',
    query:   req.query,
    entries: rows,
    schema:  schemas['audit-log'] || [],
  });
});

app.get('/reports', requireAuth, can('admin:read'), async (req, res) => {
  let rows = prismaData.getReports();
  const search = req.query.search || '';
  if (search) {
    const q = search.toLowerCase();
    rows = rows.filter(r => (r.name || '').toLowerCase().includes(q));
  }
  res.render('pages/reports/index', {
    title:   'Reports',
    slug:    'reports',
    query:   req.query,
    reports: rows,
    schema:  schemas['reports'] || [],
  });
});

app.get('/notifications', requireAuth, can('communications:read'), async (req, res) => {
  let rows = await prismaData.getNotifications();
  const search = req.query.search || '';
  const status = req.query.status || '';
  if (search) {
    const q = search.toLowerCase();
    rows = rows.filter(n =>
      (n.title || '').toLowerCase().includes(q) ||
      (n.body || '').toLowerCase().includes(q)
    );
  }
  if (status === 'READ') rows = rows.filter(n => n.readAt != null);
  else if (status === 'UNREAD') rows = rows.filter(n => n.readAt == null);
  res.render('pages/notifications/index', {
    title:         'Notifications',
    slug:          'notifications',
    query:         req.query,
    notifications: rows,
    schema:        schemas['notifications'] || [],
    statusOptions: ['', 'UNREAD', 'READ'],
  });
});

app.get('/webhooks', requireAuth, can('communications:read'), async (req, res) => {
  let rows = await prismaData.getWebhooks();
  const search = req.query.search || '';
  const channel = req.query.status || '';
  if (search) {
    const q = search.toLowerCase();
    rows = rows.filter(w =>
      (w.url || '').toLowerCase().includes(q) ||
      (w.events || []).some(ev => ev.toLowerCase().includes(q))
    );
  }
  if (channel) rows = rows.filter(w => w.channel === channel);
  res.render('pages/webhooks/index', {
    title:         'Webhooks',
    slug:          'webhooks',
    query:         req.query,
    webhooks:      rows,
    schema:        schemas['webhooks'] || [],
    statusOptions: ['', 'SLACK', 'TEAMS'],
  });
});

// ----------------------------------------------------------------------
// Role CRUD — dedicated routes (not in the auto-CRUD loop). See the
// comment block in views/lib/prismaData.js for why this is hand-written.
// express.urlencoded({extended:true}) parses `name="permissions[]"`
// repeated fields into req.body.permissions as a string[].
// NOTE: /roles/new is registered BEFORE /roles/:id so Express matches
// the literal route first when both could match (e.g. an id of "new").
// ----------------------------------------------------------------------

// GET /roles/new — admin:write gate. Only roles that can actually create
// a role (IT_MANAGER today) can see the form. Previously this was
// admin:read, which let any role with admin:read (IT_SUPPORT, AUDITOR)
// render the form they could never submit -- a UX trap and, for
// AUDITOR specifically, a perm-surface leak against the read-only role.
// POST /roles below uses the same admin:write gate so the GET-vs-POST
// surface stays in lockstep.
app.get('/roles/new', requireAuth, can('admin:write'), async (_req, res) => {
  res.render('pages/roles/new', {
    title:       'New Role',
    slug:        'roles',
    row:         { permissions: [] },
    sources:     { permissions: await prismaData.getPermissions() },
    groups:      prismaData.PERMISSION_GROUPS,
    parentCrumb: 'Admin',
    cap:         'Role',
    capLc:       'role',
    errors:      {},
  });
});

// POST /roles — create a new role with its permission set. Server-side
// builtin=false enforcement so the UI can't sneak a system role past us.
app.post('/roles', requireAuth, can('admin:write'), async (req, res) => {
  const result = await prismaData.createRole(req.body || {});
  if (!result.success) {
    return res.status(400).render('pages/roles/new', {
      title:       'New Role',
      slug:        'roles',
      row:         Object.assign({}, req.body || {}, { permissions: prismaData.parsePermissionCodes(req.body || {}) }),
      sources:     { permissions: await prismaData.getPermissions() },
      groups:      prismaData.PERMISSION_GROUPS,
      parentCrumb: 'Admin',
      cap:         'Role',
      capLc:       'role',
      errors:      result.errors,
    });
  }
  res.redirect('/roles/' + result.data.id);
});

// GET /roles/:id — read-only detail (works for builtins too, just no edit/delete buttons).
app.get('/roles/:id', requireAuth, can('admin:read'), async (req, res, next) => {
  const row = await prismaData.getRoleById(req.params.id);
  if (!row) return next();
  res.render('pages/roles/detail', {
    title:       row.name,
    slug:        'roles',
    row,
    sources:     { permissions: await prismaData.getPermissions() },
    groups:      prismaData.PERMISSION_GROUPS,
    parentCrumb: 'Admin',
    cap:         'Role',
    capLc:       'role',
    errors:      {},
  });
});

// GET /roles/:id/edit
app.get('/roles/:id/edit', requireAuth, can('admin:read'), async (req, res, next) => {
  const row = await prismaData.getRoleById(req.params.id);
  if (!row) return next();
  res.render('pages/roles/edit', {
    title:       'Edit ' + row.name,
    slug:        'roles',
    row:         Object.assign({}, row, { permissions: row.permissionCodes || [] }),
    sources:     { permissions: await prismaData.getPermissions() },
    groups:      prismaData.PERMISSION_GROUPS,
    parentCrumb: 'Admin',
    cap:         'Role',
    capLc:       'role',
    errors:      {},
  });
});

// POST /roles/:id — update an existing role. Builtin protection is
// enforced inside prismaData.updateRole (name is held; description +
// permissions remain mutable so an admin can clarify a builtin).
app.post('/roles/:id', requireAuth, can('admin:write'), async (req, res, next) => {
  const existing = await prismaData.getRoleById(req.params.id);
  if (!existing) return next();
  const result = await prismaData.updateRole(req.params.id, req.body || {});
  if (!result.success) {
    const resubmittedPerms = prismaData.parsePermissionCodes(req.body || {});
    return res.status(400).render('pages/roles/edit', {
      title:       'Edit ' + existing.name,
      slug:        'roles',
      row:         Object.assign({}, existing, req.body || {}, { permissions: resubmittedPerms }),
      sources:     { permissions: await prismaData.getPermissions() },
      groups:      prismaData.PERMISSION_GROUPS,
      parentCrumb: 'Admin',
      cap:         'Role',
      capLc:       'role',
      errors:      result.errors,
    });
  }
  res.redirect('/roles/' + req.params.id);
});

// POST /roles/:id/delete — block builtins server-side; gracefully surface
// FK-Restrict failures (users still attached to this role) as inline errors.
app.post('/roles/:id/delete', requireAuth, can('admin:write'), async (req, res) => {
  const result = await prismaData.deleteRole(req.params.id);
  if (result.success) return res.redirect('/roles');
  const row = await prismaData.getRoleById(req.params.id) || { id: req.params.id, name: 'Role' };
  res.status(400).render('pages/roles/detail', {
    title:       row.name,
    slug:        'roles',
    row,
    sources:     { permissions: await prismaData.getPermissions() },
    groups:      prismaData.PERMISSION_GROUPS,
    parentCrumb: 'Admin',
    cap:         'Role',
    capLc:       'role',
    errors:      result.errors,
  });
});

// ----------------------------------------------------------------------
// Static assets — every other file in the project root (assets/, fonts.*/,
// _DataURI/, docs/, prisma/, server.js, package.json, etc.). We do NOT
// serve *.html here; the EJS routes above own those URLs.
// ----------------------------------------------------------------------
// ----------------------------------------------------------------------
// CRUD routes for the 9 sidebar nav modules — auto-generated new / detail /
// edit / create / update / delete routes per module. Routes share the
// schemas.js field shapes (also read by mockData mutators and the
// views/partials/crud-form.ejs renderer).
// ----------------------------------------------------------------------
const schemas = require('./views/lib/schemas');

// Mapping from URL slug → mutator class name. (slugs plural → singular capitalized.)
const CRUD_SLUG_TO_NAME = {
  vendors:     'Vendor',
  locations:   'Location',
  categories:  'Category',
  users:       'User',
  assignments: 'Assignment',
  maintenance: 'Maintenance',
  licenses:    'License',
  departments: 'Department',
  approvals:   'Approval',
};

// Permission prefix per slug for the CRUD loop
const CRUD_PERM_PREFIX = {
  vendors:     'directory',
  locations:   'directory',
  categories:  'directory',
  users:       'directory',
  departments: 'directory',
  assignments: 'lifecycle',
  maintenance: 'lifecycle',
  approvals:   'lifecycle',
  licenses:    'inventory',
};

// Parent sidebar section per slug — used for the breadcrumb on new/edit/detail views.
const CRUD_PARENT = {
  vendors:     'Directory',
  locations:   'Directory',
  categories:  'Directory',
  users:       'Directory',
  assignments: 'Lifecycle',
  maintenance: 'Lifecycle',
  licenses:    'Inventory',
  departments: 'Directory',
  approvals:   'Lifecycle',
};

// Source rows for select-fk fields. Resolved once per request.
async function getSources(_slug) {
  const [categories, locations, vendors, users, assets, departments] = await Promise.all([
    prismaData.getCategories(),
    prismaData.getLocations(),
    prismaData.getVendors(),
    prismaData.getUsers(),
    prismaData.getAssetsFlat(),
    typeof prismaData.listDepartments === 'function' ? prismaData.listDepartments() : Promise.resolve([]),
  ]);
  return {
    categories,
    locations,
    vendors,
    users,
    assets: assets.map(a => ({ id: a.id, name: a.assetTag + ' — ' + a.name, assetTag: a.assetTag })),
    departments,
  };
}

// Build the locals object that a list page needs. Used by the CRUD loop when
// a modal submit fails validation — instead of rendering the standalone /new
// or /edit page, we re-render the list page with the modal pre-opened.
async function getListLocals(slug, query) {
  const sources = await getSources(slug);
  const base = { slug, query, schema: schemas[slug] || [], sources, title: TITLES[slug] || slug };
  switch (slug) {
    case 'vendors': {
      let rows = await prismaData.getVendors();
      const s = (query && query.search) || '';
      const st = (query && query.status) || '';
      if (s) { const q = s.toLowerCase(); rows = rows.filter(v => v.name.toLowerCase().includes(q) || (v.contactPerson || '').toLowerCase().includes(q) || (v.email || '').toLowerCase().includes(q)); }
      if (st) rows = rows.filter(v => v.status === st);
      return Object.assign({}, base, { vendors: rows, statusOptions: ['', 'ACTIVE', 'INACTIVE'] });
    }
    case 'locations': {
      let rows = await prismaData.getLocations();
      const s = (query && query.search) || '';
      if (s) { const q = s.toLowerCase(); rows = rows.filter(l => l.name.toLowerCase().includes(q) || (l.address || '').toLowerCase().includes(q)); }
      return Object.assign({}, base, { locations: rows });
    }
    case 'categories': {
      let rows = await prismaData.getCategories();
      const s = (query && query.search) || '';
      const t = (query && query.status) || '';
      if (s) { const q = s.toLowerCase(); rows = rows.filter(c => c.name.toLowerCase().includes(q)); }
      if (t) rows = rows.filter(c => c.type === t);
      return Object.assign({}, base, { categories: rows, statusOptions: ['', 'HARDWARE', 'SOFTWARE', 'PERIPHERAL', 'ACCESSORY'] });
    }
    case 'users': {
      let rows = await prismaData.getUsers();
      const s = (query && query.search) || '';
      const r = (query && query.status) || '';
      if (s) { const q = s.toLowerCase(); rows = rows.filter(u => u.fullName.toLowerCase().includes(q) || u.email.toLowerCase().includes(q)); }
      if (r) rows = rows.filter(u => u.role === r);
      return Object.assign({}, base, { users: rows, statusOptions: ['', 'IT_MANAGER', 'IT_SUPPORT', 'DEPARTMENT_HEAD', 'EMPLOYEE'] });
    }
    case 'assignments': {
      let rows = await prismaData.getAssignments();
      const s = (query && query.search) || '';
      if (s) { const q = s.toLowerCase(); rows = rows.filter(a => (a.assetId || '').toLowerCase().includes(q) || (a.user && a.user.fullName || '').toLowerCase().includes(q)); }
      return Object.assign({}, base, { assignments: rows });
    }
    case 'departments': {
      let rows = typeof prismaData.listDepartments === 'function' ? await prismaData.listDepartments() : [];
      const s = (query && query.search) || '';
      if (s) { const q = s.toLowerCase(); rows = rows.filter(d => d.name.toLowerCase().includes(q) || (d.code || '').toLowerCase().includes(q)); }
      return Object.assign({}, base, { departments: rows });
    }
    case 'approvals': {
      let rows = typeof prismaData.listApprovals === 'function' ? await prismaData.listApprovals() : [];
      const s = (query && query.search) || '';
      const st = (query && query.status) || '';
      if (s) { const q = s.toLowerCase(); rows = rows.filter(a => (a.entityType || '').toLowerCase().includes(q) || (a.entityId || '').toLowerCase().includes(q)); }
      if (st) rows = rows.filter(a => a.status === st);
      return Object.assign({}, base, { approvals: rows, statusOptions: ['', 'PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'] });
    }
    default: return Object.assign({}, base, {});
  }
}

for (const slug of Object.keys(CRUD_SLUG_TO_NAME)) {
  const Cap     = CRUD_SLUG_TO_NAME[slug];
  const capLc   = Cap[0].toLowerCase() + Cap.slice(1);
  const schema  = (schemas[slug]) || [];
  const hasCrud = typeof prismaData['create' + Cap] === 'function';
  const perm    = CRUD_PERM_PREFIX[slug] || 'assets'; // read/write permission prefix

  if (!hasCrud) continue;

  // GET /<slug>/:id  (detail)
  app.get('/' + slug + '/:id', requireAuth, can(perm + ':read'), async function(req, res, next) {
    const row = await prismaData['get' + Cap + 'ById'](req.params.id);
    if (!row) return next();
    // SECURITY (defense-in-depth): get<Cap>ById is already tenant-scoped
    // at the data layer (findFirst { id, tenantId: tid }), so a foreign
    // cuid normally lands in the `if (!row)` branch above and 404s via
    // the final fallback. This explicit row-level check exists so a
    // future refactor that loosens the data-layer filter (e.g. someone
    // optimising back to findUnique on a "no cross-tenant calls exist"
    // misconception) still leaves the route safe, and so the security
    // intent is documented at the call-site for anyone reading this file.
    if (row.tenantId !== req.session.tenantId) return next();
    res.render('pages/' + slug + '/detail', {
      title: row.name || row.fullName || capLc + ' ' + req.params.id,
      slug, schema, row, sources: await getSources(slug),
      capLc, cap: Cap,
      parentCrumb: CRUD_PARENT[slug] || 'IT Inventory',
      errors: {},
    });
  });

  // GET /<slug>/new
  app.get('/' + slug + '/new', requireAuth, can(perm + ':write'), async function(req, res) {
    res.render('pages/' + slug + '/new', {
      title:   'New ' + Cap,
      slug, schema,
      row:     {},
      sources: await getSources(slug),
      errors:  {},
      capLc,  cap: Cap,
      parentCrumb: CRUD_PARENT[slug] || 'IT Inventory',
    });
  });

  // POST /<slug>  (create)
  app.post('/' + slug, requireAuth, can(perm + ':write'), async function(req, res) {
    const result = await prismaData['create' + Cap](req.body || {});
    if (!result.success) {
      if (req.body._modal) {
        // Modal submit failed — re-render the list page with modal pre-opened
        const listLocals = await getListLocals(slug, {});
        return res.status(400).render('pages/' + slug + '/index', Object.assign({}, listLocals, {
          capLc, cap: Cap,
          parentCrumb: CRUD_PARENT[slug] || 'IT Inventory',
          modalErrors: result.errors,
          modalRow: req.body || {},
          modalMode: 'new',
        }));
      }
      return res.status(400).render('pages/' + slug + '/new', {
        title: 'New ' + Cap, slug, schema,
        row: req.body || {}, sources: await getSources(slug),
        errors: result.errors,
        capLc, cap: Cap,
        parentCrumb: CRUD_PARENT[slug] || 'IT Inventory',
      });
    }
    res.redirect('/' + slug + (req.body._modal ? '' : (result.data && result.data.id ? '/' + result.data.id : '')));
  });

  // GET /<slug>/:id/edit
  app.get('/' + slug + '/:id/edit', requireAuth, can(perm + ':write'), async function(req, res, next) {
    const row = await prismaData['get' + Cap + 'ById'](req.params.id);
    if (!row) return next();
    res.render('pages/' + slug + '/edit', {
      title:   'Edit ' + (row.name || row.fullName || capLc + ' ' + req.params.id),
      slug, schema,
      row, sources: await getSources(slug),
      errors:  {},
      capLc, cap: Cap,
      parentCrumb: CRUD_PARENT[slug] || 'IT Inventory',
    });
  });

  // POST /<slug>/:id  (update)
  app.post('/' + slug + '/:id', requireAuth, can(perm + ':write'), async function(req, res, next) {
    const existing = await prismaData['get' + Cap + 'ById'](req.params.id);
    if (!existing) return next();
    const result = await prismaData['update' + Cap](req.params.id, req.body || {});
    if (!result.success) {
      if (req.body._modal) {
        const listLocals = await getListLocals(slug, {});
        return res.status(400).render('pages/' + slug + '/index', Object.assign({}, listLocals, {
          capLc, cap: Cap,
          parentCrumb: CRUD_PARENT[slug] || 'IT Inventory',
          modalErrors: result.errors,
          modalRow: Object.assign({}, existing, req.body || {}),
          modalMode: 'edit',
        }));
      }
      return res.status(400).render('pages/' + slug + '/edit', {
        title: 'Edit ' + (existing.name || existing.fullName || req.params.id),
        slug, schema,
        row: Object.assign({}, existing, req.body || {}),
        sources: await getSources(slug),
        errors: result.errors,
        capLc, cap: Cap,
        parentCrumb: CRUD_PARENT[slug] || 'IT Inventory',
      });
    }
    res.redirect('/' + slug + '/' + req.params.id);
  });

  // POST /<slug>/:id/delete
  app.post('/' + slug + '/:id/delete', requireAuth, can(perm + ':write'), async function(req, res) {
    const result = await prismaData['delete' + Cap](req.params.id);
    if (result.success) return res.redirect('/' + slug);
    // delete failed — re-render the detail page with the FK blocker surfaced
    const row = await prismaData['get' + Cap + 'ById'](req.params.id) || { id: req.params.id };
    res.status(400).render('pages/' + slug + '/detail', {
      title: row.name || row.fullName || capLc + ' ' + req.params.id,
      slug, schema,
      row, sources: await getSources(slug),
      errors: result.errors,
      capLc, cap: Cap,
      parentCrumb: CRUD_PARENT[slug] || 'IT Inventory',
    });
  });
}

// ----------------------------------------------------------------------
// Static assets — locked-down allowlist.
// Previously this was `app.use(express.static(ROOT_DIR, ...))` which
// served the WHOLE project root. That leaked:
//   - /prisma/schema.prisma + /prisma/seed.js (the seed contains bcrypt
//     hashes of every demo account's password — credential disclosure)
//   - /server.js (full Express routing code)
//   - /views/lib/*.js (e.g. prismaData.js — exposes DB query patterns
//     and DB role names like 'c13-tech', so an attacker could fingerprint
//     staging/prod internals)
//   - /package.json + /package-lock.json (deps + start scripts)
//   - /tmp/, /ref/, /scripts/ (working + reference HTML)
//   - any future file dropped into the project root that nobody hand-
//     denied.
// New policy:
//   1. Explicit denylist enforced FIRST — belt-and-suspenders so even if
//      someone widens the static list later, these paths cannot leak.
//   2. Three explicit allowlisted mounts only — /assets, the local
//      mirror of /fonts.googleapis.com/css2, and /fonts.gstatic.com/*
//      IBM Plex Sans WOFF2. Anything else falls through to the 404.
// ----------------------------------------------------------------------

// Defense-in-depth denylist — two layers:
//   1. STATIC_PATH_DENYLIST matches /<block> or /<block>/... for sensitive
//      top-level directories and files. Each variant is spelled out so
//      near-miss names (e.g. `/.envguide` or `/prismajsconfig`) are NOT
//      flagged by the regex.
//   2. STATIC_EXT_DENYLIST matches a filename ending in .log / .bak / .swp /
//      .DS_Store (with optional ?<query> for cache-busting clients).
//
// The mounts below already exclude these, but if a future maintainer
// re-adds `app.use(express.static(ROOT_DIR, ...))` we still don't leak
// source code / seed credentials / IDE config / env files / runtime logs.
// Path-prefix denylist. `\.env(?:\.[a-z][a-z0-9_-]*)?` accepts any future
// `.env.<lowercase-segment>` (e.g. `.env.staging`, `.env.qa`) without an
// edit here, AND does NOT match `.envguide`/`.envnotes` (no dot before
// the trailing word). Root-level git hygiene files (.gitattributes,
// .gitmodules, .dockerignore) live OUTSIDE .git/ so they need explicit
// alts; without them they would be served.
// Defense-in-depth PATH denylist. Each att is either:
//   - a literal top-level directory / file                     (e.g. prisma, server.js)
//   - a dotted git ignore / syntax file                        (e.g. .gitignore, .envrc)
//   - a top-level infrastructure file                          (e.g. Dockerfile, docker-compose)
//   - one with an OPTIONAL dotted-variant suffix               ((?:\.[\w]+)? / (?:\.[\w][\w.-]*)?)
//
// Tightened env matcher `\.env(?:\.[\w][\w.-]*)?` (was `\.env(?:\.[a-z][a-z0-9_-]*)?`):
//   - DENIES: /.env, /.env.local, /.env.production.local,
//             /.env.development.local, /.env.staging.local, /.env.<stage>.<scope>
//   - ALLOWS: /.envguide, /.envtest, /.envnotes, /.envguide/sub  (no dot after .env)
//
// Variant suffixes use `[\w.-]+` so multi-dot filenames like
// `Dockerfile.prod.local` are still denied.
const STATIC_PATH_DENYLIST = /^\/(?:prisma|views|scripts|server\.js|package\.json|package-lock\.json|\.env(?:\.[\w][\w.-]*)?|\.envrc|\.git|\.gitignore|\.gitattributes|\.gitmodules|\.gitconfig|\.dockerignore|Dockerfile(?:\.[\w.-]+)?|docker-compose(?:\.[\w.-]+)?|Makefile|\.editorconfig|\.babelrc(?:\.[\w.-]+)?|\.eslintrc(?:\.[\w.-]+)?|\.eslintignore|\.prettierrc(?:\.[\w.-]+)?|\.browserslistrc|\.stylelintrc(?:\.[\w.-]+)?|tsconfig\.json|\.github|\.vscode|\.npm|\.npmrc|\.nvmrc|\.idea|\.vercel|tmp|ref)(?:\/.*)?$/i;
const STATIC_EXT_DENYLIST = /\.(?:log|bak|swp|DS_Store)(?:$|\?)/i;
app.use((req, res, next) => {
  if (STATIC_PATH_DENYLIST.test(req.path) || STATIC_EXT_DENYLIST.test(req.path)) {
    // Return a plain 404 (not 403) so unauthenticated probing doesn't
    // confirm the URL exists.
    return res.status(404).end();
  }
  next();
});

// Explicit allowlist — the ONLY paths static middleware will serve.
//   /assets/*                 — CSS, JS, fonts, images used by the UI
//   /fonts.googleapis.com/*   — local mirror of the Google Fonts stylesheet
//   /fonts.gstatic.com/*      — local mirror of the IBM Plex Sans WOFF2
// Anything outside these prefixes is a 404 → falls through to the final
// 404 handler below.
app.use('/assets',             express.static(path.join(ROOT_DIR, 'assets'),             { index: false, extensions: false }));
app.use('/fonts.googleapis.com', express.static(path.join(ROOT_DIR, 'fonts.googleapis.com'), { index: false, extensions: false }));
app.use('/fonts.gstatic.com',  express.static(path.join(ROOT_DIR, 'fonts.gstatic.com'),  { index: false, extensions: false }));

// Final fallback: render the 404 EJS view with a 404 status.
app.use((_req, res) => {
  res.status(404).render('pages/pages-404', { title: TITLES['pages-404'] || '404' });
});

// Try to bind to PORT; if it's busy (EADDRINUSE), increment the port and retry.
// Prevents nodemon from crash-looping when 3000 is held by another app.
function listenWithFallback(app, startPort, host, maxAttempts) {
  return new Promise((resolve, reject) => {
    let port = startPort;
    let attempts = 0;

    const tryOnce = () => {
      const server = app.listen(port, host);

      server.once('listening', () => {
        resolve({ server, port, attempts });
      });

      server.once('error', (err) => {
        if (err.code === 'EADDRINUSE' && attempts < maxAttempts) {
          attempts += 1;
          console.warn(`[server] Port ${port} is in use, trying ${port + 1}...`);
          port += 1;
          setImmediate(tryOnce);
        } else {
          reject(err);
        }
      });
    };

    tryOnce();
  });
}

listenWithFallback(app, PORT, HOST, MAX_PORT_ATTEMPTS)
  .then(({ server, port, attempts }) => {
    if (attempts > 0) {
      console.log(`[server] Bound after ${attempts} retry(ies).`);
    }
    console.log(`\nClarity server running at http://${HOST}:${port}`);
    console.log(`Dashboard:  http://${HOST}:${port}/`);
    console.log(`Login page: http://${HOST}:${port}/auth-login.html`);
    console.log('Press Ctrl+C to stop.\n');

    // Graceful shutdown — drain in-flight HTTP requests, then disconnect
    // the Prisma client so its connection pool is released back to Postgres.
    // Without this, every Ctrl+C / nodemon restart / pkill silently leaks
    // open connections until Postgres reaps them — quickly exhausting
    // max_connections during dev/test churn (the classic
    // "FATAL: sorry, too many clients already" symptom).
    const shutdown = async (signal) => {
      console.log(`\n[server] Received ${signal}, shutting down...`);
      server.close(async (err) => {
        if (err) console.error('[server] Error during server.close():', err.message);
        try {
          await prisma.$disconnect();
          console.log('[server] Prisma disconnected, exiting cleanly.');
        } catch (e) {
          console.error('[server] Error disconnecting Prisma:', e.message);
        }
        process.exit(0);
      });
      // If a hung request prevents `server.close()` from firing, force-exit
      // but FIRST try a best-effort $disconnect so we don't leak sockets —
      // this is the exact path the original bug exposed.
      setTimeout(() => {
        console.warn('[server] Graceful shutdown timed out, forcing exit.');
        prisma.$disconnect()
          .catch((e) => console.error('[server] Force-exit disconnect failed:', e.message))
          .finally(() => process.exit(1));
      }, 5000).unref();
    };
    process.on('SIGINT',  () => shutdown('SIGINT'));
    process.on('SIGTERM', () => shutdown('SIGTERM'));

    // Last-resort safety nets — if Node crashes (uncaught throw or
    // unhandled rejection), still disconnect Prisma so we never leak DB
    // sockets, even on the unhappy path.
    process.on('uncaughtException', async (err) => {
      console.error('[server] Uncaught exception:', err);
      try { await prisma.$disconnect(); } catch (e) { console.error('[server] Disconnect after exception failed:', e.message); }
      process.exit(1);
    });
    process.on('unhandledRejection', async (reason) => {
      console.error('[server] Unhandled rejection:', reason);
      try { await prisma.$disconnect(); } catch (e) { console.error('[server] Disconnect after rejection failed:', e.message); }
      process.exit(1);
    });
  })
  .catch((err) => {
    console.error(`\n[server] Failed to start: ${err.message}`);
    if (err.code === 'EADDRINUSE') {
      console.error(
        `[server] Tried ports ${PORT}..${PORT + MAX_PORT_ATTEMPTS - 1} — all in use.\n` +
        `        Free one up, or pick a different range, e.g.:\n` +
        `          PORT=4000 npm start`
      );
    }
    process.exit(1);
  });
